### ISSUE TITLE
problem jeedom 4.2.4 and access rights (.htaccess)

### ISSUE THREAD

**Issue by nicoca-ine** [BadWolf42/jMQTT#107]
HI,
Since jeedom 4.2.4 upgrade, images of jMQTT are not visible probably due to an access rights issue:

![image](https://user-images.githubusercontent.com/8222318/137115200-7bbcf69a-4768-4876-a89f-cfcb2e83b8d0.png)

**Comment by BadWolf42** [comment]
Must change images folder name to img in data folder.

Refs:
https://community.jeedom.com/t/plus-dimage-dans-le-plugin/69073/
https://community.jeedom.com/t/probleme-affichage-logos-dans-jmqtt/69137/

**Comment by Domochip** [comment]
Waiting for clear position from Jeedom.
Images need to be moved to "core/img" or "desktop/img"?

**Comment by BadWolf42** [comment]
Hi @nicolaschiret, could you check last beta?
It should be fixed.

**Comment by nicoca-ine** [comment]
Hi.
I will try on Wednesday, not at home for few days.
Thanks

**Comment by nicoca-ine** [comment]
Hi,
It's ok. Issues on icons has gone.
Tks
