### ISSUE TITLE
Impossible to send commands

### ISSUE THREAD

**Issue by florentin68** [BadWolf42/jMQTT#110]
I'm using Jeedom beta 4.2.5 and i'm experiencing that no commands are understood any more by zigbee2mqtt since last beta release.
zigbee2mqtt log tells me `Invalid message 'null', skipping...` for this message received: 
```
Debug Received MQTT message on 'zigbee2mqtt/0x60a423fffe62161d/set' with data '{'state': 'ON'}'
Error Invalid message 'null', skipping...
```
I think this is related to string delimiters used `'` instead of `"`.
The Jeedom cmd has this properties:
Topic: `zigbee2mqtt/0x60a423fffe62161d/set`
Value: `{"state":"ON"}`
Retain: `No`
QoS: `Empty`

Do you think my explanation is correct? I don't have z2m log in debug level prior to the bug to compare.

**Comment by florentin68** [comment]
It is sure. I've tested this in command line which works:
` mosquitto_pub -m '{"state":"ON"}' -t "zigbee2mqtt/0x60a423fffe62161d/set"`

z2m log:
```
Debug Received MQTT message on 'zigbee2mqtt/0x60a423fffe62161d/set' with data '{"state":"ON"}'
Debug Publishing 'set' 'state' to '0x60a423fffe62161d'
```

**Comment by BadWolf42** [comment]
Continuing [this discution](https://community.jeedom.com/t/erreur-envoi-de-commandes-jmqtt-vers-zigbee2mqtt/70080/21) here.

On v4.2 even after removing commit https://github.com/Domochip/jMQTT/commit/31832d581dba544bc0449ff2bc74a22b695a4cb6, Jeedom Core breaks JSON content by replacing `"` by `'`.

Need to investigate if those PR on Jeedom were enough:
https://github.com/jeedom/core/pull/1825
https://github.com/jeedom/core/pull/1829

**Comment by Domochip** [comment]
@Florentin68 Could you validate that problem is solved for you using jMQTT beta branch. thanks

**Comment by florentin68** [comment]
I tried beta branch from Jeedom market.
It is ok again to send commands in JSON format.
I also noticed that on the plugin's equipment list view, the icons are correctly shown again because there was an HTML error before which leads to empty images (403 I think, maybe a problem with a .htaccess rule).
Thank you.
