### ISSUE TITLE
Template carte dingtian 8 relais

### ISSUE THREAD

**Issue by Jeandhom** [BadWolf42/jMQTT#116]
https://fr.aliexpress.com/item/4000999069820.html?spm=a2g0o.placeorder.0.0.5b156ef8HFEJEp&mp=1

[dingtian8Relay.zip](https://github.com/Domochip/jMQTT/files/7529370/dingtian8Relay.zip)

**Comment by Domochip** [comment]
voici le visuel : 
![image](https://user-images.githubusercontent.com/33293764/141512681-a54ff18d-cef8-41d3-aae4-6e28c8eda148.png)
Est-ce celui attendu?
Toutes les commandes du bas servent-elles à quelques choses? : 
![image](https://user-images.githubusercontent.com/33293764/141512811-9f37f106-0e75-4331-b100-086e5473b3aa.png)

Si non, il vaut mieux les supprimer et désactiver l'Ajout automatique des commandes surl'équipement : 
![image](https://user-images.githubusercontent.com/33293764/141512916-a3366b85-010e-4c39-ab2d-9fcd8092cf80.png)

**Comment by Jeandhom** [comment]
Voici le résultat chez moi.

![Capture d’écran du 2021-11-12 19-08-13](https://user-images.githubusercontent.com/49077193/141514461-63907f11-f550-4eda-9a94-5e313840455f.png)

Je laisse toujours tout et je désactive l'affichage au cas ou j'aurai besoin d'autre chose.
De même, je laisse l'ajout automatique par habitude avec le matériel shelly qui est très prolifique en nouveaux firmwares et donc en nouveaux topics.

**Comment by Domochip** [comment]
OK, j'avais pas élargi.
template publié en beta

**Comment by Jeandhom** [comment]
Merci pour les autres utilisateurs de cette carte.
