### ISSUE TITLE
[idea] create template with datas from official zwave repo

### ISSUE THREAD

**Issue by pifou25** [BadWolf42/jMQTT#120]
https://github.com/Domochip/jMQTT/projects/1#card-60234017

@Domochip 
> Créer une moulinette de création de template de device à partir des infos des repo de zigbee2mqtt, Zwavejs2Mqtt, etc...

L'idée est louable et je voudrais la faire passer à "to do" :D Mais surtout, c'est trop vaste et trop vague en l'état, je voudrais pour commencer essayer de reformuler... (en fait je suis en plein migration de mon réseau zwave vers mqtt et donc ça me donne des idées!)

via MQTT on reçoit une masse d'informations, tant sur les commandes et informations, que sur le type de module (code produit, fabriquant, type modèle liste des commandes et informations disponibles et tout ça) (et aussi, pour le z-waveJs2mqtt on a le nom & location)
Pour cette idée on veut utiliser toutes ces informations de configuration, et je pense que l'idée peut se résumer ainsi:

> Créer des règles de création d'objets MQTT à partir des informations de configuration reçues par des "émetteurs" spécifiques (ZwaveJs2Mqtt, Zigbee2Mqtt, et / ou autre peu importe) et surtout, créer le "moteur de règles" correspondant

Je vais proposer quelques règles qui sont spécifiques au zwave mais le moteur de règle qui analyse ces règles et crée les objets, lui doit être générique.
```
zwave/Bureau/Chauffage/nodeinfo
{
  "id": 13,
  "name": "Chauffage",
  "loc": "Bureau",
  "neighbors": [],
  "ready": true,
  "available": true,
  "failed": false,
  "inited": true,
  "hexId": "0x0060-0x0004-0x0008",
  "dbLink": "https://devices.zwave-js.io/?jumpTo=0x0060:0x0004:0x0008:1.2",
  "manufacturerId": 96,
  "productId": 8,
  "productType": 4,
  "deviceConfig": {
    "filename": "/usr/src/app/store/.config-db/devices/0x0060/an179.json",
    "isEmbedded": true,
    "manufacturer": "Everspring",
    "manufacturerId": 96,
    "label": "HAN02",
    "description": "In-Wall Switch Module",
    "firmwareVersion": {
      "min": "0.0",
      "max": "255.255"
    },
  },
  "productLabel": "HAN02",
  "productDescription": "In-Wall Switch Module",
  "manufacturer": "Everspring",
  "firmwareVersion": "1.2",
  "protocolVersion": 3,
  "zwavePlusVersion": 1,
  "zwavePlusNodeType": 0,
  "zwavePlusRoleType": 5,
  "nodeType": 1,
  "isSecure": false,
  "security": "None",
  "supportsSecurity": false,
  "supportsBeaming": true,
  "isControllerNode": false,
  "isListening": true,
  "isFrequentListening": false,
  "isRouting": true,
  "deviceClass": {
    "basic": 4,
    "generic": 16,
    "specific": 1
  },
  "deviceId": "96-8-4",
  "status": "Alive",
  "interviewStage": "Complete",
}
```
1ère règle, à partir du topic nodeinfo on peut créer le "eqLogic" au sens jeedom "chauffage" dans le "bureau" (si l'objet bureau est créé dans jeedom) avec quelques infos de base (produit label versions, status, etc...)
> zwave/(objet)/(eqlqogic)/nodeinfo{ ... }
et dans le payload json, capturer les informations requises (ou optionnelles) pour valoriser dans le eqLogic.

2ème étape, pour générer des commandes maintenant. 2 solutions:
* soit on se base sur la base des templates existants, qu'il faudra donc bien relier à un module (marque & modèle mais aussi sans doute version), et hop, SI on reconnait un module on peut alors créer toutes les commandes automatiquement.
* soit on pousse l'automatisme un peu plus loin et on défini de nouvelles règles spécifiques à la création de commandes :

> zwave/(objet)/(eqLogic)/50/0/(\d)

La règle doit être simple je pense, du genre créer une commande info 'info1' sur l'objet / eqLogic détecté, de type info numérique pour le topic détecté. Il faudrait trouver une spécification de ces chiffres mais je pense qu'on n'en a pas beaucoup, le 1er (112 ici dans mon exemple) c'est toujours les mêmes valeurs qui reviennent:
* 37  pour un switch binaire (current value + target value)
* 38 pour un dimmer (valeur variable de 1 à 255, commande & info)
* 50 pour un capteur, une mesure (valeur numérique à priori mais aucune commande)
* 91 pour un mode scène...

Une règle ressemble à une expression régulière, mais ça reste un outil propre au plugin, ce n'est pas à l'utilisateur d'implémenter ses règles. Je veux dire que, à mon sens, le plugin doit être livré avec la liste des règles "clé en main", mais ça permet juste de distinguer les règles propres à zwave, zigbee & co, on pourra les regrouper dans un "catalogue de règles" par protocole.

La 2e idée implicite évidemment vous l'aurez compris c'est: "créer le moteur de règles" :D qui sera capable de valider la syntaxe des règles, puis les exécuter.

merci de m'avoir lu!

Pour rigoler, sur mon jeedom de test j'ai importé l'objet topic zwave/# (!) du coup j'ai plein d'exemples de topics et de payload si vous voulez.

**Comment by BadWolf42** [comment]
Bonjour @pifou25,

On a tourné et retourné cette idée dans nos têtes depuis un moment, sans pour autant te faire de retour. 
Il serait effectivement possible de reprendre tous les `nodeinfo` de zwave2mqtt et de les décliner sous forme de templates, mais il faudrait alors aussi s'occuper de zigbee2mqtt, OpenMQTTGateway, voir d'autres encore ([et la liste est longue](https://project-awesome.org/hobbyquaker/awesome-mqtt)).

Malheureusement, le travail d'intégration à réaliser pour parvenir à supporter tous ces protocoles indépendamment est beaucoup trop grand. Nous avons donc décidé de travailler plutôt sur le support d'[Home Assistant MQTT Discovery](https://www.home-assistant.io/docs/mqtt/discovery/) qui est souvent déjà implémenté par les différentes solution vers MQTT.
Sans fournir des templates toute faites, cela permettra de créer rapidement des équipements utilisables, à partir des annonces qu'ils réalisent à travers ce protocole. 

C'est déjà un très gros chantier en soi, à priori c'est faisable, mais il faut encore le confirmer. En tout cas, des transformations sont en cours en `beta` pour valider la faisabilité de la chose.

Merci pour ton enthousiasme sur le projet,
Bad
