### ISSUE TITLE
Problème inclusion et message "Unexpected error between WebSocket Daemon and Python Daemon"

### ISSUE THREAD

**Issue by StephaneG38** [BadWolf42/jMQTT#121]
Bonjour,
Je n'arrive plus à inclure un nouvel équipement qui est pourtant bien visible sous MQTT Explorer.
J'ai également le message "Unexpected error between WebSocket Daemon and Python Daemon" toute les 5 minutes.
Le Broker est au vert et mes équipement déjà installé sont fonctionnels.
Je suis passé sur la version Beta (2021-12-07 01:01:16) en lisant une Issue sur le même sujet mais pas mieux.
Je suis sur RPI3B+ avec Jeedom 4.1.27
J'utilise également Zigbeelinker en version Z2M + Client MQTT.
Ci-joint mes logs
Merci par avance
Stéphane
[Logs JMQTT.zip](https://github.com/Domochip/jMQTT/files/7699009/Logs.JMQTT.zip)

**Comment by Domochip** [comment]
Bonjour,

Pourriez-vous passer le plugin en mode debug comme ceci : 
![image](https://user-images.githubusercontent.com/33293764/145723782-f4e191f0-fbaa-4a6a-ab98-6314b1e17661.png)

Puis refournir du log à nouveau.
Merci

**Comment by StephaneG38** [comment]
Bonjour,
Ci-joint les logs en mode debug 
[Logs JMQTT2.zip](https://github.com/Domochip/jMQTT/files/7699285/Logs.JMQTT2.zip)

**Comment by Domochip** [comment]
Je doit ajouter du texte au message d'erreur.
Il y a 2 possibilités pour lesquels je vous donnerais les instructions: 
 - modifier un fichier du plugin sur votre jeedom
 - passer votre plugin en beta

Laquelle pourriez-vous réaliser?

**Comment by StephaneG38** [comment]
Je peux modifier le fichier sur mon jeedom

**Comment by Domochip** [comment]
parfait, alors voici ce qu'il faut ajouter : 

![image](https://user-images.githubusercontent.com/33293764/145727825-78d39d50-e54d-4afc-9692-29d779528ef9.png)

cela devrait donner plus de détails sur l'erreur

**Comment by StephaneG38** [comment]
J'ai déjà les lignes présentes
![image](https://user-images.githubusercontent.com/38179281/145728119-ca7c9c73-5f3c-43d5-aeab-7221e4af1ee4.png)

**Comment by StephaneG38** [comment]
Normalement je suis sur la Beta.
Cela explique peux être que les lignes sont présentes ?

**Comment by Domochip** [comment]
Arf, je l'avais juste mis en surbrillance dans l'editeur, désolé, voici ce qu'il faut ajouter : 
![image](https://user-images.githubusercontent.com/33293764/145772020-dab8b05a-a324-4a07-b7a8-5455999cd8fd.png)

**Comment by StephaneG38** [comment]
Bonjour,
Je viens de faire la modif et j'ai un nouveau message 
`	Id 426 : Unexpected error between WebSocket Daemon and Python Daemon : Frame must be coalesced before applying mask`

**Comment by StephaneG38** [comment]
Ci-joint les nouveaux logs 
[logs JMQTT-3.zip](https://github.com/Domochip/jMQTT/files/7702659/logs.JMQTT-3.zip)
au cas ou

**Comment by kwetnico** [comment]
Je vais me permettre juste de mettre un commentaire pour suivre la discussion car j'ai eu le même message l'autre jour lors de l'ajout d'un nouveau périphérique même si cela a tout de même créé le périph.

**Comment by Domochip** [comment]
Je soupçonne un payload trop gros mais il faut encore faire des tests.

**Comment by StephaneG38** [comment]
Ok
Je peux aider comment ?

**Comment by Domochip** [comment]
désolé pour l'ambiguïté, les tests sont à faire de notre coté.
Il faut determiner à partir de quelle taille ca dysfonctionne.
Jeter un oeil de chaque coté (Serveur PHP Ratchet ou librairie python websocket-client) pour savoir lequel ne respecte pas le standard et si une configuration permet d'outrepasser le problème.
(Je me demande aussi si la configuration PHP ne tronque pas le message et du coup, bam)

**Comment by StephaneG38** [comment]
Un peu trop compliqué pour moi !
Je patiente donc que les pros trouvent la solution
Merci pour votre aide.
Stéphane

**Comment by BadWolf42** [comment]
Hello, ayant aussi le problème chez moi, j'ai passé mosquitto en debug et jmqtt aussi

**Comment by BadWolf42** [comment]
J'ai réussi à reproduire !

Initialement, le problème s'est posé avec un message de 76157 octets sur le topic `zigbee2mqtt/bridge/devices`.

Avec les commandes suivantes, j'ai pu générer des messages de 64607 et 64608 octets, et les envoyer au broker :
```
base64 /dev/urandom | head -c 64607 > 64607.txt
base64 /dev/urandom | head -c 64608 > 64608.txt
mosquitto_pub -h 192.168.11.2 -t teleinfo/pouet -f 64607.txt
mosquitto_pub -h 192.168.11.2 -t teleinfo/pouet -f 64608.txt
```
Le premier message passe, le second non.
Tous les messages (que j'ai testé) avec une taille de plus de 64608 octets ont entrainés un plantage de ratchet chez moi.

```
PHP Warning:  unpack(): 64-bit format codes are not available for 32-bit versions of PHP in /var/www/html/plugins/jMQTT/resources/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php on line 163
[2021-12-13 20:50:54][ERROR] : Id 501 : Unexpected error between WebSocket Daemon and Python Daemon : Frame must be coalesced before applying mask
[2021-12-13 20:50:54][DEBUG] : Id 501 : Python daemon disconnected from WebSocket Daemon
```

@Domochip, je te laisse essayer chez toi.

Le "fix" vu ensemble (https://groups.google.com/g/ratchet-php/c/NbXI8YPj_eQ) NE FONCTIONNE PAS

Le fix semble être d'[installer php 64bits](https://github.com/ratchetphp/Ratchet/issues/792) ?!

**Comment by Domochip** [comment]
Sur ma VM de test ca marche (VM x64) : pas d'erreur.
Tu as testé sur quoi?

**Comment by BadWolf42** [comment]
Sur un Pi3

**Comment by Domochip** [comment]
Il doit y avoir une différence de traitement/configuration entre un RPi et une machine x86/64.
Reste déjà à savoir si ca vient du client websocket ou du daemon python.
faut regarder si on peut : 
- soit sniffer le traffic websocket
- soit activer un log debug sur le websocket-client

l'idée est de voir si il y a une différence

**Comment by kwetnico** [comment]
Perso j'ai eu le message d'erreur sur un pi4

**Comment by Domochip** [comment]
J'ai ressorti mon RPi3 et j'arrive aussi à le reproduire.
j'ai activé le debug coté client Python, mais l'envoi semble être le même.
De plus certains résultat sur l'Internet semble pointer vers un problème du coté de Ratchet PHP plutot (daemon PHP)
ex1 : https://stackoverflow.com/questions/69301995/sending-websocket-message-greater-than-64kb-causes-ratchet-websocket-server-to-t
ex2 : https://github.com/ratchetphp/Ratchet/issues/792

une librairie de RatchetPHP est-elle en cause ou bien ratchet lui-même?

**Comment by StephaneG38** [comment]
Hello,
Pour info j'ai fait la Maj 2021-12-14 01:01:10 et j'ai toujours le message et pas d'inclusion possible
Bon courage
Stéphane

**Comment by StephaneG38** [comment]
Bonjour,
Pour info MAJ 2021-12-15 01:01:17 faite ce matin et toujours pas mieux.
Je continue à faire les MAJ beta ou pas ?
Stéphane

**Comment by BadWolf42** [comment]
Fix temporaire dans le PR #123.

Pour le moment c'est quick & dirty mais fonctionnellement jMQTT n'y perd rien : on supprime les messages de plus de 65535 octets, afin d'éviter le crash du daemon PHP.

A voir si on passe ce PR rapidement en stable et si le niveau de log "ERROR" des messages "Ignoring >=64Ko message" est OK.

Dans le futur, il faudra :
- Soit découper les messages, et identifier coté php si le topic est utilisé et si on doit rassembler le message ou non
- Soit supprimer le daemon PHP selon le travail commencé sur ma branche "remove-php-daemon"

**Comment by StephaneG38** [comment]
Hello,
J'attend la prochaine MAJ de la Beta pour avoir le Fix temporaire ?

**Comment by BadWolf42** [comment]
Oui, ou bien tu peux appliquer directement le fix en changeant le code de cette façon : 
https://github.com/Domochip/jMQTT/pull/123/files#diff-7a4c783a639f1c767111fb2b9d701872d25a53095c2ba4385b851196a6cc0f5eR162-R206

**Comment by StephaneG38** [comment]
Donc j'ajoute les lignes en vert dans le fichier jmqttd.py  et je relance les dépendances et le démon ?

**Comment by StephaneG38** [comment]
J'ai une erreur 
![image](https://user-images.githubusercontent.com/38179281/146229937-6ba2b550-78d5-43f9-80dd-593eef3f12a4.png)

**Comment by BadWolf42** [comment]
Il est important d'utiliser des espaces, pas des tabs, quand tu colle le code ;)
En règle générale, l'indentation est cruciale en Python

**Comment by StephaneG38** [comment]
OK
Je ne connais pas du tout ce langage
Je vais réessayer

**Comment by StephaneG38** [comment]
Il faut relancer les dépendance ou seulement le démon ?

**Comment by BadWolf42** [comment]
Juste le Daemon

**Comment by StephaneG38** [comment]
Dac

**Comment by StephaneG38** [comment]
YESSSSS
Super ca fonctionne !!
Plus de message et inclusion de nouveau possible !
Bravo et encore merci pour le travail !!
Stéphane

**Comment by BadWolf42** [comment]
De rien !
Comme dit, c'est un fix temporaire, le temps d'aller vers une solution plus pérenne.

**Comment by StephaneG38** [comment]
OK
La modif sera dans la prochaine Stable ?

**Comment by kwetnico** [comment]
J'ai pu inclure mon périphérique malgré le message d'erreur.
Cependant depuis ce jour j'ai un périphérique qui envoie aléatoirement les informations la journée sous jmqtt alors que zigbee2mqtt reçoit bien l'information toutes les heures.. Y'a t'il un lien ou rien à voir ?

Merci

**Comment by BadWolf42** [comment]
Il ne devrait pas y avoir de lien
Regarde dans les logs si le message de ton périphérique est bien envoyé à Jeedom au moment où la valeur est publiée en mqtt par la source, sinon ouvre une autre issue avec quelques traces stp.

**Comment by Domochip** [comment]
Je n'avais pas bien lu les premières analyse de @BadWolf42 
Voici la véritable source de l'erreur qu'il avait donné: 
`PHP Warning:  unpack(): 64-bit format codes are not available for 32-bit versions of PHP in /var/www/html/plugins/jMQTT/resources/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php on line 163`

Il s'agit d'un appel à unpack dans Ratchet qui lève une exception parcequ'on lui demande de sortir 8 octets dans un entier de 64bits sur un PHP 32bits (pas possible d'instancier des entiers de 64 bits).

Par chance, cet entier doit contenir la taille du payload et si on demande de sortir les 4 derniers octets (dans un entier de 32 bits donc), cela permet un fonctionnement normal pour un payload de 2Go. Ce qui parait tout à fait logique.

J'ai pu modifier le code de Ratchet sur mon Jeedom 32bits et le faire fonctionner.
Voici la version modifiée que j'ai écrite rapidement (modification peu avant la ligne 163): 
[MessageBuffer.php.txt](https://github.com/Domochip/jMQTT/files/7723140/MessageBuffer.php.txt)

Je pense qu'une PR à Ratchet est envisagable avec une version mieux écrite/plus élégante..

**Comment by StephaneG38** [comment]
Hello,
Pour info suite à la mise à jour de ce matin (2021-12-21 01:01:09) le message est revenu et impossible de faire des inclusions.
J'ai remis mon fichier modifié et tout est ok
Stéphane

**Comment by BadWolf42** [comment]
Bonjour @StepG38, 
C'est parfaitement normal : le patch qui tu as appliqué manuellement n'est pas présent dans la mise à jour de ce matin.
Il faut donc que tu le repasses.

@Domochip, peux-tu intégrer temporairement mon PR, le temps que ratchetphp fix leur code ?

**Comment by StephaneG38** [comment]
Ok merci pour la réponse.
Stéphane

**Comment by Domochip** [comment]
Plutot que de lever des erreurs ou bloquer les messages, je voyais plutot un patch bien sale de la librairie en question lors de l'install des dépendances.

genre : Si OS==32bits alors remplacer "unpack('J', $bytesToUpack)[1]" par "unpack('N2', $bytesToUpack)[2]" dans le fichier MessageBuffer.php

Qu'en penses-tu?

**Comment by BadWolf42** [comment]
Je pense qu'il ne faut pas patcher à la volée une lib, surtout si elle est téléchargée dynamiquement, c'est la porte ouverte à d'autres problèmes plus tard.
Quand on peut adapter le code pour palier au pb, il faut le faire sans attendre une maj de la lib.
Je n'ai pas l'impression que ça avance d'ailleurs...

Si tu veux, on peut adapter les logs pour ne pas remonter d'erreur sauf en Debug.

**Comment by Domochip** [comment]
Ce ne serait pas à la volée, mais juste après la step d'installation de la librairie RatchetPHP.
ici : https://github.com/Domochip/jMQTT/blob/952de9191b1c8740a7f9a6458a5b7abf68874db6/resources/install_apt.sh#L64

Le truc c'est qu'en adaptant notre code, on ne palie pas vraiment au problème.
Alors qu'en patchant, c'est pleinement fonctionnel.

**Comment by BadWolf42** [comment]
De mon point de vue, c'est juste une question de limite.
Si plus de 64ko ça plante et ça se relance, ok, mais personne ne râle par ce qu'il ne reçoivent pas les messages de plus de 64ko.
Donc autant faire au plus simple et moins impactant pour nous et ignorer les messages problématiques.

Mon avis c'est que : si des gens se plaignent de PB avec les messages 64ko on verra pour patcher plus profondément, mais c'est juste mon avis, c'est toi qui décide.

**Comment by kwetnico** [comment]
Bonjour,

Pour information, j'ai installé la mise à jour de zigbeemqtt 1.22.2 sur mon PI4 et à la fin de l'installation lorsque le service a redémarré sous jeedom j'ai eu l'erreur du plugin JMQTT qui c'est affiché : 

ID41 : Unexpected error between WebSocket Daemon and Python Daemon (pas de log supplémentaire pourtant mode DEBUG activé)

**Comment by StephaneG38** [comment]
Bonjour @BadWolf42  et @Domochip ,
Pouvez-vous me dire si je dois mettre à jour en stable ou en Beta et si je dois systématiquement remplacer le fichier jmqttd.py par la version modifiée ensemble ?
Merci par avance
Stéphane

**Comment by StephaneG38** [comment]
Bonjour @BadWolf42 et @Domochip,
Vous pouvez me répondre SVP !

**Comment by BadWolf42** [comment]
Pour le moment, aucun des codes, beta ou stable, n'intègre le correctif.
Nous attendons une réponse de la part des développeurs de la bibliothèque qui contient le bug.

**Comment by Domochip** [comment]
Dernière relance au propriétaire de la librairie qui est à l'origine du problème.
Si pas de réponse, on mettra en place une mesure correctrice demain ou après-demain.

**Comment by StephaneG38** [comment]
OK merci pour le retour.
Je touche rien pour le moment
Merci encore
stéphane

**Comment by Domochip** [comment]
@BadWolf42 dsl, j'ai préféré l'option patch de la librairie : d4c41486c7264acfdaad895c0a71f00233153e50
C'est beta.

**Comment by Domochip** [comment]
Oups, j'ai oublié le if 32bits.
Je corrige

**Comment by Domochip** [comment]
Doit être résolu par la dernière release (https://github.com/Domochip/jMQTT/pull/127)

**Comment by Domochip** [comment]
@StepG38 tu confirmes?

**Comment by kwetnico** [comment]
J'ai installé la nouvelle stable, j'ai du relancer l'installation des dépendances et relancer le service, pas vue d'erreurs pour l'instant.

**Comment by StephaneG38** [comment]
Hello,
Effectivement cela fonctionne sur la stable.
Merci beaucoup à vous deux !!
