### ISSUE TITLE
Message cannot be published, daemon is not connected to the broker

### ISSUE THREAD

**Issue by Pme1159** [BadWolf42/jMQTT#124]
Hello, I have problems to set up the communication between Jeedom and Home Assistant. The messages of Jeedom are not published.

Content of  the file Jmqtt_HA :
[2021-12-15 21:14:02][INFO] : démarre le client MQTT 
[2021-12-15 21:14:02][INFO] : Equipement MQTT Détecteur Cuisine: subscribes to "jeedom" with Qos=1
[2021-12-15 21:14:02][INFO] : Subscribes to the API topic "jeedom/api"
[2021-12-15 21:14:02][INFO] : Broker HA: subscribes to "jeedom/api" with Qos=1
_(and when I test the action in the equipment)_
[2021-12-15 21:14:26][INFO] : <- MQTT Détecteur Cuisine|jeedom/temperature 20.7
[2021-12-15 21:14:26][DEBUG] : Publishing message jeedom/temperature 20.7 (qos=1, retain=0)
[2021-12-15 21:14:26][WARNING] : Message cannot be published, daemon is not connected to the broker
[2021-12-15 21:15:02][INFO] : démarre le client MQTT 
[2021-12-15 21:15:02][INFO] : Equipement MQTT Détecteur Cuisine: subscribes to "jeedom" with Qos=1
[2021-12-15 21:15:02][INFO] : Subscribes to the API topic "jeedom/api"
[2021-12-15 21:15:02][INFO] : Broker HA: subscribes to "jeedom/api" with Qos=1

When I connect with Putty to Jeedom and I introduce the command "mosquitto_sub ...", I get a message : bash mosquitto-sub commande introuvable"
But Mosquitto is installed on the virtual machine of Home Assistant (address IP introduced in the field IP/Nom de domaine du Broker.

Please find herein  a copy of the health of Jeedom :
![image](https://user-images.githubusercontent.com/59808783/146263197-b0d1d827-1300-4608-a8b0-dfc60971c9b3.png)

I thank you in advance for your support and thank you for your plugin.
Pascal (pme1159)

**Comment by Domochip** [comment]
Hello, 

You can first install mosquitto_sub by running the following install command : 
`apt install mosquitto-clients`

**Comment by Pme1159** [comment]
Hello Domochip and thank you for your prompt answer. I have installed mosquitto_sub on my jeedom virtual machine using Putty. When I launch the command I get the following answer now : 
![image](https://user-images.githubusercontent.com/59808783/146345174-9383b9f9-2e93-4f80-92cd-1021760e9e43.png)

No changes in Jeedom jMQTT. Always the same content in the log :  
[2021-12-16 10:32:42][INFO] : <- MQTT Détecteur Cuisine|jeedom/temperature 20.7
[2021-12-16 10:32:42][DEBUG] : Publishing message jeedom/temperature 20.7 (qos=1, retain=0)
[2021-12-16 10:32:42][WARNING] : Message cannot be published, daemon is not connected to the broker

Thank you in advance.

**Comment by BadWolf42** [comment]
`All subscription requests were denied` reflects a credential issue.
Do you use certificate and/or login/pwd to connect to mosquitto Broker?
If so, you need to adapt mosquitto_sub call or mosquitto Broker configuration.

**Comment by Pme1159** [comment]
No, I don't use certicates nor login/pwd to connect to mosquitto broker.

For your information, as I don't know if this may be link to my issue, I had also to change yesterday the value "Port démon python" from 1025 to 1027 as I had the following error message : 
"Erreur sur la fonction deamon_start du plugin : Le port du démon python (1025) est déjà utilisé par le pid 1138 : python3 /var/www/html/plugins/jMQTT/resources/jmqttd/jmqttd.py --plugin jMQTT --loglevel error --socketport 1025 --apikey QLjOhFNAsVQkVkXXXXXXXhwgY6dKC8p --pid /tmp/jeedom/jMQTT/jmqttd.py.pid" 
This morning, I tried to come back to the value 1025 and it seems working.
![image](https://user-images.githubusercontent.com/59808783/146377024-dce18696-bf3f-4a10-97b4-0447d5ec55b9.png)

But I have always the same message "All subscription requests were denied" when I launch the command mosquitto_sub ...

**Comment by Pme1159** [comment]
Do you think I should try to connect to a local broker instead of the broker installed by Home Assistant ?
In this case, is it possible by selecting the field "Installer Mosquitto localement" and by running again the installation of the "dépendances" ?

**Comment by BadWolf42** [comment]
I think that Broker of Home Assistant is "restrained" or "secured" and this is the problem.
Could you check the configuration of HA MQTT Broker?
(https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md)

**Comment by Pme1159** [comment]
Hello and thank you. I will try this next week when I come back as I have to leave now for abroad for a few days.
Pascal

**Comment by Domochip** [comment]
Hello, 
Does everything work fine now for you?

**Comment by Pme1159** [comment]
Yes. It si fine now. I forgot to inform you. I'm sorry for that. It was as you said a problem of authorization in home assistant. I forgot to install a user in HA. Thank you for your support.
