### ISSUE TITLE
JMQTT - Jeedom 4.1.28  Dépendances  NOK   Relance des dépendances impossible 

### ISSUE THREAD

**Issue by edesmaret** [BadWolf42/jMQTT#126]
Bonjour,

J'ai lancé une MAJ générale de ma box Jeedom PRO (version 4.1.28). 
Depuis, JMQTT ne se lance plus et lorsque je relance les dépendances, il s'arrête soit à 60% soit à 80%.

J'ai supprimé puis réinstallé le plugin. Même résultat.

Que faire ?

Merci d'avance pour votre assistance.

**Comment by BadWolf42** [comment]
Bonjour @edesmaret,

Es-tu en stable ou en beta sur jMQTT ?
Peux-tu passer en debug et nous donner les logs de l'installation des dépendances ?

Merci,
Bad

**Comment by edesmaret** [comment]
Bonjour
Merci pour votre email.

Oui JMQTT fonctionnait avant les mises à jour.
C'est la version 3.3.24 stable du 29.11.2021 qui est installée.
Log des dépendances en PJ. on voit  des bad cmmmands.

[image: image.png]


Merci d'avance pour votre assistance.

Regards,
Eric DESMARET

**Comment by Domochip** [comment]
Bonjour,

Je vous conseille plutot de vous rendre sur la page de l'issue afin de répondre  : https://github.com/Domochip/jMQTT/issues/126

L'image jointe n'apparait pas malheureusement. Pourriez-vous la rajouter.

Un point m'échappe, dans le premier message, il est indiqué `version 4.1.28` puis dans le dernier `version 3.3.24`.
Un restauration a-t-elle été effectuée entre temps?

Quelle est la version de debian ( `cat /etc/debian_version` )?

**Comment by edesmaret** [comment]
Bonjour

La version 4.1.28 est celle de la jeedom box PRO
3.3.24 est la version de JMQTT
J'ai mis la copie d'écran en PJ.

Regards,
Eric DESMARET

M : +230 5 716 44 71

**Comment by Domochip** [comment]
Je vous conseille plutot de vous rendre sur la page de l'issue afin de répondre.
L'image n'apparait toujours pas.

Quelle est la version de debian ( cat /etc/debian_version )?

**Comment by edesmaret** [comment]
cat /etc/debian_version
10.4
![NOS-BUG-JMQTT-20220112](https://user-images.githubusercontent.com/97537961/149123024-70b140cd-5660-41ef-acdd-71048095ead9.PNG)

**Comment by Domochip** [comment]
OK, il nous faut le log d'installation des dépendances pour identifier l'erreur.
Voici comment les trouver : 
![image](https://user-images.githubusercontent.com/33293764/149124207-5b72d702-084d-4c92-9fc9-0d266a357d55.png)

Ensuite l'idéal est de le télécharger : 
![image](https://user-images.githubusercontent.com/33293764/149124311-679cf03d-47b9-426d-be9b-f5bf2bc3bc0c.png)

et de le poster ici pour qu'on y jette un oeil

**Comment by edesmaret** [comment]
je les avais déjà envoyé dans mon mail.

je les remets ici en P
[jMQTT_dep_logs.zip](https://github.com/Domochip/jMQTT/files/7853881/jMQTT_dep_logs.zip)
J

**Comment by Domochip** [comment]
Alors, la première chose qui m'étonne est la suivante : 
Il y a une erreur à la première étape : 
```
*
* Synchronize the package index
*
Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
```

Qui n'est autre qu'un simple `sudo apt-get update`
Pourriez-vous l'executer manuellement pour voir? Un redemarrage de Jeedom a-t-il été fait (une autre installation serait en cours qui aurait locké?)

**Comment by edesmaret** [comment]
je viens de lancer le sudo apt-get update

cela semble se dérouler correctement (voir PJ).
J'ai essayé de relancer l'ins
[jMQTT_dep_analyse_2.zip](https://github.com/Domochip/jMQTT/files/7854502/jMQTT_dep_analyse_2.zip)
tallation des dépendances de JMQTT mais ça bug encore.
je mets les 
[jMQTT_dep_analyse_2.zip](https://github.com/Domochip/jMQTT/files/7854503/jMQTT_dep_analyse_2.zip)
nouveaux logs en PJ.

**Comment by Domochip** [comment]
OK, maintenant, il faut essayer d'installer python3-wheel avec la commande suivante : 
`sudo apt-get install -y python3-wheel`

**Comment by edesmaret** [comment]
Installation de python3-wheel OK -> see results in attachment
Installation des dépendances de JMQTT OK -> see results as well.

Merci à vous,
Eric
![NOS-BUG-JMQTT-20220112 -003-Fixed_issuePNG](https://user-images.githubusercontent.com/97537961/149151665-d51b387d-c599-4fef-9d1b-7bf47cdc6aa4.PNG)
![NOS-BUG-JMQTT-20220112-003-sudo_apt-install_python3-wheel](https://user-images.githubusercontent.com/97537961/149151672-a1b8c8b6-cf2f-4883-bc5e-af9fbb718e3d.PNG)

**Comment by Domochip** [comment]
OK, parfait.
je vais ajouter cette dépendance explicitement dans jMQTT.
Si tout fonctionne maintenant pour vous, vous pouvez fermer cette issue avec le bouton Close juste en dessous.

**Comment by edesmaret** [comment]
thank you for your assistance.
