### ISSUE TITLE
Template manager améliorations

### ISSUE THREAD

**Issue by pifou25** [BadWolf42/jMQTT#129]
Bonjour,

Suite aux discutions sur le community à propos des templates et des normes de nommage - en particulier pour zwave mais je suppose qu'on aurait le même problème pour d'autres protocoles.

- **root topic** : aujourd'hui tous les topics d'un objet ont la même racine `zwave/location/equipment` par exemple, et le template remplace tout le 'root topic' sans distinction par celui de l'objet à utiliser. On voudrait pouvoir utiliser un autre topic pour interroger l'API de ZwaveJs avec ce préfixe: `zwave/_CLIENTS/ZWAVE_GATEWAY-Zwavejs2Mqtt/api/` Ceci est une constante pour mon installation, mais dans le cadre des échanges de template ça ne l'est plus, dépend du paramétrage zwavejs2mqtt:
![image](https://user-images.githubusercontent.com/20190031/149679850-a32fec6b-1dde-4170-84eb-26486b5fa333.png)

- Toujours pour améliorer l'échange de templates, on voudrait pouvoir rappeler une autre commande dans la valeur d'une commande. 2 exemples:

1.  valeur de la commande
![image](https://user-images.githubusercontent.com/20190031/149679929-7fd21ff1-ddc8-4c26-a2ed-c9d0ad3f2dc1.png)
Une commande `nodeId` me donne une info (le node id de l'équipement). Pour la 2e commande, j'utilise dans le json envoyé la valeur de cette info: `{"args": [#[salon][Ampoule2][nodeId]#]}` Mais dans le template c'est remplacé par l'id de cette commande sur mon jeedom `{"args:[#2462#]}`. Il faudrait, lors de la création du template, numéroter toutes les commandes de 1 à N, et utiliser cet id à la place de mon id perso. Puis, lorsqu'on applique un template sur un objet, on remplace cet id par le "human name" de la commande concernée.

2. autre action de la commande
![image](https://user-images.githubusercontent.com/20190031/149680137-4548863e-2962-4092-b63a-95e108ad776d.png)
Pareil que précédemment, j'utilise cette fois une "action à effectuer avant la commande" sur mon propre objet `#[salon][Ampoule2][SetRed]#` (puis setBlue, setGreen, ...) Les actions sont correctement exportées dans le template, mais ici encore avec mon #id# perso:
```
"jeedomPreExecCmd": [
    {
        "options": {
            "enable": "1",
            "background": "1",
            "slider": "hexRed(#color#)"
        },
        "cmd": "#28502#"
    },
```
La même correction fonctionnera ici aussi: numéroter les commandes de 1 à N lors de la création du template, et remplacer ces numéros lors qu'on applique un template sur un objet.

[Je me suis inspiré de cette discussion pour mémoire](https://community.jeedom.com/t/jmqtt-partage-de-template/71743/43?u=pifou)

**Comment by BadWolf42** [comment]
Hello @pifou25,

Demain en beta il y aura une amélioration des templates, en rapport avec ta demande :
- Lors de l'export d'un équipement en template, les commandes de l'équipement (source) au format `#1234#` (cmd id) présentes dans d'autres commandes sont transformées en `#[Nom de la commande]#` (dite "commande nommée"),
- Lors de l'application d'un template à un équipement, les "commande nommée" sont remplacées par les id des commandes de l'équipement (cible) correspondantes.

La beta passera probablement en stable fin de semaine, mais si tu veux tester que ça répond à ton cas d'usage, nous en serions ravi. Je vais fermer ce vieux ticket car la fonctionnalité est implémentée, mais tu peux répondre dessus si tu constates des dysfonctionnements avant le passage en stable.

Bad
