### ISSUE TITLE
The indent is removed in sending

### ISSUE THREAD

**Issue by pirracas77** [BadWolf42/jMQTT#141]
Hello:

I have seen a problem with the indent in a message sent to my point of charge:

When I send a message like that 

{
"ID_TRANS":"7435",
"DATE":"2022-02-13 08:56:58",
"POWER_LIMITS":{
"P_MAX":3750
}
}

jMQTT transformed it  into  

`{"ID_TRANS":"7435","DATE":"2022-02-13 08:56:58","POWER_LIMITS":{"P_MAX":3750}}`

(I can see in notepad++ that the "CRLF" at the end of each line was removed)

For a reason that I don't undertand yet, this is a problem in the receiver when you send several messages very often in a short period of time and finally it stucks and stops sending back the ACKs or any other message .

I can send many messages in a sort period of time using for example "MQTT explorer" that respects the ident with no problems, but when I do the same with jMQTT I start to be in troubles.

Could you tell me how can I force to keep the ident in jMQTT? Maybe the "JSON_PRETTY_PRINT" flag is missed somewhere in your code. (?)

I put an image with two examples captured, one sent by jMQTT (9:13)  the other with MQTT explorer (8:56) .

![image](https://user-images.githubusercontent.com/18216098/153744835-3ea82561-3c79-4c1d-ad61-f1a3588db165.png)

Thanks in advance.

(P.S: As a workaround,  I'm using mosquitto_pub with "-f" option sending a file with the ident right)

**Comment by BadWolf42** [comment]
Hello @pirracas77,

I assume that you are running jMQTT stable and Jeedom Core 4.2 ?

I think this issue is linked to modification of `jeedom::evaluateExpression()` function in core, modifies the data to include tags and do calculations, as we do not manipulate the data before publishing.

**Comment by pirracas77** [comment]
> Hello @pirracas77,
> 
> I assume that you are running jMQTT stable and Jeedom Core 4.2 ?
> 
That's right.

**Comment by BadWolf42** [comment]
Hello @pirracas77,
We discussed this issue with @Domochip and there is no way we can prevent effectively Jeedom to modify the payload.
So I'm going to close this issue.
Bad

**Comment by pirracas77** [comment]
@BadWolf42 But in the jmqtt, the ident  is well saved

![image](https://user-images.githubusercontent.com/18216098/154534924-2a1a3055-4d15-410e-bd16-77aa65592e62.png)


![image](https://user-images.githubusercontent.com/18216098/154535395-c32d47d0-5aa2-470d-927f-c8fa70c25c09.png)


Are you telling me that jeedon is modifying previous to the sending ?

**Comment by BadWolf42** [comment]
Yes, this is linked to the modification of `jeedom::evaluateExpression()` function in core.

Since those 2 commits [c6887fd](https://github.com/jeedom/core/commit/c6887fd884d86517388cd0a2ed658939f70fefa6) & [430f004](https://github.com/jeedom/core/commit/430f0049dc74e914c4166b109fb48b4375f11ead), `jeedom::evaluateExpression()` is now interpreting the content of the payload field and replaces json by a PHP array()...
So in that cas we have to re-encode in json the content of the payload, see here: 
https://github.com/Domochip/jMQTT/blob/bd8339a356a5fc05a3fbb62bbbe578151aa92b9b/core/class/jMQTT.class.php#L1798-L1801

We have to use `jeedom::evaluateExpression()` before publishing the message, in order to replace tags and do calculation on the payload when needed:
https://github.com/Domochip/jMQTT/blob/bd8339a356a5fc05a3fbb62bbbe578151aa92b9b/core/class/jMQTTCmd.class.php#L192-L227

**Comment by pirracas77** [comment]
Thanks @BadWolf42  for the quick asnwer (as usually)

I have tried next just in case but nothing happends (I restarted the demon) . So it seems an issue with no solution as you warned me.

`$payload = json_encode($payload,JSON_UNESCAPED_UNICODE,JSON_PRETTY_PRINT);`

**Comment by Domochip** [comment]
Hi,

You wrote : 
`For a reason that I don't undertand yet, this is a problem in the receiver when you send several messages very often in a short period of time and finally it stucks and stops sending back the ACKs or any other message .`
I think you need to focus on the receiver.
What is this receiver? a specific hardware? a software?

**Comment by pirracas77** [comment]
> Hi,
> 
> You wrote : `For a reason that I don't undertand yet, this is a problem in the receiver when you send several messages very often in a short period of time and finally it stucks and stops sending back the ACKs or any other message .` I think you need to focus on the receiver. What is this receiver? a specific hardware? a software?

Is this one. But don't care. I will stop with this issue here.

https://www.orbis.es/produits/mobilite-electrique/chargeurs-intelligents-pour-environnements-prives/monophases/viaris-combi-230-v

**Comment by BadWolf42** [comment]
I missed that, can you explain why do you `send several messages very often in a short period of time` ?

Can't you delay the send, or check if a message was not sent in the last X seconds ?

Maybe with a scenario that checks when the last message was sent and if you can send again

**Comment by pirracas77** [comment]
> I missed that, can you explain why do you `send several messages very often in a short period of time` ?
> 
> Can't you delay the send, or check if a message was not sent in the last X seconds ?
> 
> Maybe with a scenario that checks when the last message was sent and if you can send again

The behaviour is weird. Sometimes it stucks just with one message sometimes with several. The point is that only happens if the ident is missed. (I use mosquitto_pub as workaround and it works like a charm)

I have photovoltaic energy, so I modulate the charging power based on my solar surpluses.
