### ISSUE TITLE
Création d'un template pour WeConnect

### ISSUE THREAD

**Issue by jbval** [BadWolf42/jMQTT#146]
Bonjour,

en me branchant sur le mqtt de ce projet :
https://github.com/tillsteinbach/WeConnect-mqtt
j'ai créé un template sommaire pour une id3.
Il est applicable en ciblant ce topic (pour éviter de récupérer beaucoup d'informations non affichageable) : weconnect/0/vehicles/VinDuVehicule/#

Le fichier est disponible ici : https://github.com/jbval/jeedomMqttCustomTemplates/blob/main/Id3WeConnectMqttLight.json
Si ça peut intéresser..

**Comment by BadWolf42** [comment]
Bonjour jbval, 
je vais intégrer ton template directement dans jmqtt.
Merci encore

**Comment by BadWolf42** [comment]
Merged in PR #156
