### ISSUE TITLE
Erreur depuis passage à la version du 2802022 (dernière version)

### ISSUE THREAD

**Issue by mchacher** [BadWolf42/jMQTT#152]
J'utilise jMQTT depuis plusieurs années. Merci pour le travail !
Depuis la dernière mise à jour j'obtiens des erreurs sur toutes mes réceptions de message en provenance de mes objets domotiques perso. Je m'explique, chaque objet domotique transmet une trame json comme celle-ci par exemple pour un simple capteur de température.
```
topic : lora2mqtt/NODE_10 
valeur : {"T":"22.3","#tx":786}
```
L'erreur reçue est la suivante : `Chemin JSON de la commande lora2mqtt|NODE_10{tx} incorrect : "[#tx]"`

Je suppose que jMQTT n'apprécie pas que l'information tx soit préfixée par **#**, chose qui était parfaitement supportée auparavent.

Pouvez vous confirmer ? et corriger le cas échéant ?

Merci à vous

**Comment by BadWolf42** [comment]
Bonjour @mchacher,

Il doit manquer des guillements autour du Chemin json :
![image](https://user-images.githubusercontent.com/8396512/158028265-f094e5fd-a4f1-4cf3-8e7f-efc39951e81a.png)

Peux-tu essayer de les rajouter ?
Tiens nous au courant,
Bad

**Comment by mchacher** [comment]
Bonjour @BadWolf42,

en effet ceci semble corriger le problème. En revanche quand je passe en vue JSON il propose automatique la valeur #tx sans guillemet. Voir exemple ci-dessous.
![image](https://user-images.githubusercontent.com/9514230/158029586-b713303c-6057-4139-ab7d-e68b008f9d22.png)
Merci pour le support !

**Comment by BadWolf42** [comment]
@Domochip,

Il me semblait qu'on avait fixé via ce commit :
https://github.com/Domochip/jMQTT/commit/ef1f46fbf88781c110b7dbb149b034559862ab04

Il va probablement falloir échapper tout ce qui n'est pas strictement alphanumérique, non ?

Bad

**Comment by Domochip** [comment]
Yep

On avait paré au plus préssé avec point, espace et slash mais j'ai zappé qu'on devait faire les autres.

**Comment by BadWolf42** [comment]
Au final, ce serait peut être moins contraignant et plus logique de tout mettre entre quotes et échapper les quotes, non ?

**Comment by BadWolf42** [comment]
Bonjour @mchacher,

Je viens d'implémenter le patch suivant pour ce bug :
```
----------------------------- desktop/js/jMQTT.js -----------------------------
@@ -485,8 +485,8 @@ function printEqLogic(_eqLogic) {
 			var this_id = addPayload(topic, jsonPath, payload, parent_id);
 			for (i in payload) {
 				var escapedi = i;
-				if (escapedi.includes('.') || escapedi.includes(' ') || escapedi.includes('/')) {
-					escapedi = '\'' + escapedi + '\'';
+				if (escapedi.match(/[^\w-]/)) { // Escape if a special character is found
+					escapedi = '\'' + escapedi.replace(/'/g,"\\'") + '\'';
 				}
 				if (typeof payload[i] === 'object') {
 					recursiveAddJsonPayload(topic, jsonPath + '[' + escapedi + ']', payload[i], this_id);
```
Ce bug est normalement résolu dans la branch `dev` et passera en `beta` dans les prochains temps.
Si tu souhaites tester, tu peux faire sans crainte la modification sur ton fichier `desktop/js/jMQTT.js`.

Souhaites-tu que nous gardions cette issue ouverte pour te prévenir quand elle sera résolue en beta ou stable ?

Bad

**Comment by mchacher** [comment]
Merci à toi. Si on peut laisser ouvert avant le passage en stable c'est parfait.

**Comment by BadWolf42** [comment]
Passage de ce correctif en beta le 30 mai 2022

**Comment by BadWolf42** [comment]
Bonjour @mchacher, as-tu pu vérifier en beta que ce correctif corrige bien dans ton cas ?

**Comment by BadWolf42** [comment]
Bonjour @mchacher, le correctif est en stable, as-tu pu vérifier ?

**Comment by BadWolf42** [comment]
Problème corrigé en stable
