### ISSUE TITLE
RING devices templates (with ring-mqtt)

### ISSUE THREAD

**Issue by nicoca-ine** [BadWolf42/jMQTT#154]
Hi,

With this, I'll share templates working with RING Alarm (and somes of his devices). And for RING Doorbell and RING Indoor Cam
[RING_Templates.zip](https://github.com/Domochip/jMQTT/files/8342352/RING_Templates.zip)
.

Tks for your work !!

**Comment by nicoca-ine** [comment]
[RING_Templates_v2.zip](https://github.com/Domochip/jMQTT/files/8356384/RING_Templates_v2.zip)
new version without custom command for RING Base Station sound level (linked to virtual cursor info in my jeedom). Just to be more neutral.

More info:[https://community.jeedom.com/t/tuto-ring-avec-ring-mqtt-et-jmqtt/81595](https://community.jeedom.com/t/tuto-ring-avec-ring-mqtt-et-jmqtt/81595)

**Comment by BadWolf42** [comment]
Hello @nicolaschiret,

Your templates will be merged in PR #156 as: _RING_Alarm_Base_Station, RING_Alarm_Control_Panel, RING_Camera, RING_Contact_Sensor, RING_Doorbell_Chime, RING_Doorbell_Pro, RING_Keypad, RING_Motion_Sensor, RING_Range_Extender_.

Please recheck if all the templates are ok for you (some naming changes happened).
If OK or NOK, please comment ok PR #156.

Many thanks 🥰
