### ISSUE TITLE
Fonction HTMLtoXY dans la class jMQTTCmd

### ISSUE THREAD

**Issue by Jeandhom** [BadWolf42/jMQTT#157]
La variable $color et l'array éponyme semblent se télescoper dans cette fonction.
J'ai remplacé la variable $color par $_color pour que cela fonctionne.

`public static function HTMLtoXY($_color)
{

$_color = str_replace('0x', '', $_color);
$_color = str_replace('#', '', $_color);
$red = hexdec(substr($_color, 0, 2));
$green = hexdec(substr($_color, 2, 2));
$blue = hexdec(substr($_color, 4, 2));

**Comment by BadWolf42** [comment]
Hello,
Merci pour le signalement.
En effet, la variable $color est initialement utilisée comme string puis comme array.
Je viens de faire un PR pour intégrer la modif.

Je peux clore ton issue ou tu souhaites la garder ouverte et qu'on te prévienne quand ce sera intégré en beta et en stable ?

Bad

**Comment by Jeandhom** [comment]
Merci pour votre travail.
Tu peux clore l'issue, j'ai fait la modif chez moi.
