### ISSUE TITLE
problème de rafraichissement état/commandes dans Design

### ISSUE THREAD

**Issue by dandcs** [BadWolf42/jMQTT#174]
Bonjours,

Suite à la reprise de paramètres d'affichage dans Design, j'ai eu une série du message joint "Centre.message.jeedom.txt", je ne comprends pas le lien entre mes actions dans Design et ce qui semble être une erreur jMQTT. J'ai constaté pouvoir par exemple allumer une lampe par Design, mais ne plus pouvoir l'éteindre et pas de rafraichissement de son icone graphique état.

[Centre message Jeedom.txt](https://github.com/Domochip/jMQTT/files/8939298/Centre.message.Jeedom.txt)

Quels éléments supplémentaires, dois je vous apporter ?

Merci d'avances pour vos retours.

**Comment by BadWolf42** [comment]
Bonjour @dandcs,

Peux-tu expliquer ce que tu entends pas "reprise de paramètres d'affichage dans Design" ?

> J'ai constaté pouvoir par exemple allumer une lampe par Design, mais ne plus pouvoir l'éteindre et pas de rafraichissement de son icone graphique état.
Ca ressemble plus à un problème d'association de commande ou de widget.

Le log fournit est effectivement en rapport avec un autre problème connu que nous sommes en passe de régler par la suppression du daemon php:
https://community.jeedom.com/t/multiple-erreurs-mysql-duplicate-entry/84388
https://community.jeedom.com/t/on-mqtt-message-raised-an-exception-mysql-error-code-23000-1062-duplicate-entry/85201
https://community.jeedom.com/t/message-jmqtt/81860/4

Est-tu as l'aise pour tester la version de la branch "dev" ?
Le daemon php y est supprimé, elle tourne très bien sur ma prod (depuis 3j).

Bad

**Comment by dandcs** [comment]
Bonjour BadWolf42,

Je n'ai pas constaté de message particuliers ces derniers jours par le centre de message. Ce matin, j'ai juste voulu ajuster un peu l'aspect graphique de mes différentes vues dans Accueil \ Design (comme ci dessous)
![2022-06-20_173533](https://user-images.githubusercontent.com/84261847/174636459-8e3af94c-d612-4ec9-a757-4bbff5bcbb34.png)

Puis, un message (celui renseigné au début du topic) est apparu de manière répété. 
J'ai ensuite pensé à regarder les log de JMQTT et j'ai remarqué qu'un des équipements (même pas celui sur lequel je testais le fonctionnement) générait beaucoup d'erreur de type " Duplicte entry" et "jeedom.object doesn't exist".
Quand je cliquais sur le bouton slide on/off de la lampe, j'arrivais à faire le premier changement d'état, mais pas le deuxième et aucun rafraichissement de l'état.
Comme cela doit le faire ci dessous :
![2022-06-20_173533](https://user-images.githubusercontent.com/84261847/174638644-afa48238-de4f-4dd8-bf51-95ff5120c0a8.png)
![2022-06-20_174758](https://user-images.githubusercontent.com/84261847/174638719-c6bbdcb3-2cad-4d8b-aa85-59d454305142.png)

Je ne comprends pas trop comment ce problème est arrivé, j'ai fini par décider de restaurer à une sauvegarde faite tôt ce matin (avant apparition du problème) et pour l'instant tout semble se maintenir correctement. 

Si je comprends bien, le JMQTT doit évoluer, je reste ouvert à la possibilité de la passer en "dev" comme tu le suggère, dés fois que je puisse t'apporter des renseignements sur son fonctionnement. Comment dois-je procéder ?

**Comment by BadWolf42** [comment]
Hello @dandcs,

> Puis, un message (celui renseigné au début du topic) est apparu de manière répété.
J'ai ensuite pensé à regarder les log de JMQTT et j'ai remarqué qu'un des équipements (même pas celui sur lequel je testais le fonctionnement) générait beaucoup d'erreur de type " Duplicte entry" et "jeedom.object doesn't exist".

Ca c'est effectivement en rapport avec le daemon php

> Quand je cliquais sur le bouton slide on/off de la lampe, j'arrivais à faire le premier changement d'état, mais pas le deuxième et aucun rafraichissement de l'état.

Peux-tu me faire une capture de la configuration de l'équipement en question ? Un truc a pu sauter.

Pour passer en branch dev, il faut aller dans "Plugins> Gestion des plugins", puis faire comme si tu ajoutais un nouveau jMQTT et ne surtout pas désinstaller le plugin jMQTT avant :
![image](https://user-images.githubusercontent.com/8396512/174744694-2278ef38-dae3-4c19-8184-16fd4685e2b6.png)
```
Type de source:       Github
ID logique du plugin: jMQTT
Utilisateur du dépôt: Domochip
Nom du dépôt:         jMQTT
Branche:              dev
```
Un fois sauvegardé, tu peux vérifier que les dépendances sont bien isntallée (normalement oui, il y en a moins et que le daemon est bien lancé et tu sera en version dev.

Passe bien le daemon et les brokers en Debug pour avoir un maximum de détails (il n'est plus nécessaire de redémarrer le daemon pour qu'il en soit informé dans cette version).

Perso, je constate une conso memoire plus faible et stable et aucune erreur "Duplicate entry" depuis.

Ensuite, si besoin, pour repasser en stable ou en beta, il suffit simplement d'installer le plugin depuis le market, comme si jMQTT n'était pas encore installé (mais toujours sans désinstaller jMQTT avant).

Bad

**Comment by dandcs** [comment]
Bonjour Bad,

Ci dessous la capture de la configuration de l'équipement en cause, il était déclaré depuis longtemps. Après l'envoi de mon message précédent, j'ai modifié un paramètre, car j'avais remarqué qu'il était enregistré avec 'Ajout automatique de commandes" de coché. (décoché depuis). Tous est toujours fonctionnel depuis.
![image](https://user-images.githubusercontent.com/84261847/175209870-f60939e7-6d5b-44cf-8188-dc2c5104f9bd.png)

Merci pour ta description de  passage en "dev" de JMQTT. Je l'ai donc passé ce matin en dev. Tout est ok. Je te ferais des retour si choses etranges constatées, et n’hésites pas à me demander des éléments si je peux aider à faire avancer le dev.
![Sélection_108](https://user-images.githubusercontent.com/84261847/175214049-2664cfea-674d-432b-a9b7-67d27b0eb2f6.png)

Merci encore.

**Comment by BadWolf42** [comment]
Merci pour ton retour, peux-tu aussi me faire une capture des commandes de ton équipement ?

**Comment by dandcs** [comment]
les voici :
![Sélection_109](https://user-images.githubusercontent.com/84261847/175220285-79ffb419-aebf-4ac4-b561-e5f2bcb4f8d5.png)
![Sélection_110](https://user-images.githubusercontent.com/84261847/175220296-3723d604-8667-4525-854a-b367962aa153.png)

**Comment by BadWolf42** [comment]
Je te recommande de mettre `relay:0` dans le champ de "Commande information liée" de tes commandes `On` et `Off` : 
![image](https://user-images.githubusercontent.com/8396512/175227664-77c34168-aad4-4434-994d-d52614e1dc2f.png)

C'est ça qui pilote normalement l'état des widgets.

**Comment by BadWolf42** [comment]
Bonjour @dandcs,

Est ce que ton problème est résolu ?
Tu peux repasser sur la branche beta, la branche dev y a été poussée et de nouvelles mise à jour arrivent encore ce jour.

Pour rappel : pour repasser en beta, il suffit simplement d'installer le plugin en beta depuis le market, comme si jMQTT n'était pas encore installé (mais toujours sans désinstaller jMQTT avant).

**Comment by dandcs** [comment]
Bonjour Bad,

En effet plus de problème avec JMQTT, je rebascule donc en beta, suite à ton conseil. Merci.


⁣Télécharger TypeApp pour Android ​

Le 3 juil. 2022 à 08:34, à 08:34, Bad ***@***.***> a écrit:

**Comment by BadWolf42** [comment]
Merci pour ton retour, bonne continuation avec le plugin, ravi qu'il te rende le service attendu ;)
