### ISSUE TITLE
Bug aprés mise à jour

### ISSUE THREAD

**Issue by ThomasJee95** [BadWolf42/jMQTT#179]
Suite à notre conversation [Logs jM.txt](https://github.com/Domochip/jMQTT/files/8991214/Logs.jM.txt)

J'hésite à faire une restauration.. j'ai peur que ça se passe mal !

Merci ;)

**Comment by BadWolf42** [comment]
Hello, 

Je viens de regarder les logs, en résumé :
- Dépendances : OK,
- Démon Python : OK
- Démon PHP : Fréquents crashs/déconnexions de WebSocketClient -> peu d'importance dans ce cas
- ThBroker : OK
- Log généraux jMQTT : 124 exceptions `on_mqtt_message` en ~30 minutes !
Exceptions `[MySQL] Error code : 22001 (1406). Data too long for column 'value' at row 1  : REPLACE INTO history`...
Générées par des messages sur les topic `POW-2/tele/STATE` et `POW-2/tele/SENSOR`

**Mon analyse :** il existe 2 commandes info (probablement de type "Autre") qui souscrivent au topic `POW-2/tele/SENSOR`. Ces commandes sont historisées et les fonctions d'historisatio de Jeedom ne supportent pas des infos de type Autre aussi grande.

**Solution possible :** Désactiver l'historisation sur ces 2 commandes. Normalement, il n'est même pas nécessaire de les conserver et ces commandes peuvent être supprimées, car les informations pertinentes sont probablement présentes dans d'autres commandes info (de type Numérique ou Binaire) et il n'est pas nécessaire de garder le topic racine pour que son contenu soit analysé.

Dans tous les cas, il n'est vraiment pas recommandé d'historiser des commandes info de type autre, surtout quand elles reçoivent autant de mises à jour et ce cette taille, cela fait gonfler la base de donnée pour rien et ralenti Jeedom.

Tiens moi au courant si ça résout ton problème.

Bad

(Lien Commu pour référence : https://community.jeedom.com/t/panne-suite-a-maj-de-jmqtt-peux-on-revenir-en-arriere/86541)

**Comment by BadWolf42** [comment]
Bonjour @ThomasJee95,

Tu peux nous donner des nouvelles de ton problème ?

Merci

**Comment by ThomasJee95** [comment]
Bonjour,
Je vous avais répondu et remercié mais peut être pas au bon endroit !
J'ai donc désactivé les historisation et même purgé l'historique, et tout est rentré dans l'ordre !
Un grand merci à vous :)  et félicitation pour ce plugins qui me sert tous les jours !

**Comment by BadWolf42** [comment]
Merci pour ton retour, bonne continuation avec le plugin, ravi qu'il te rende le service attendu ;)
