### ISSUE TITLE
probleme envoi de Json stocké dans un virtuel

### ISSUE THREAD

**Issue by KipK** [BadWolf42/jMQTT#208]
Hello

Je rencontre un petit soucis sur jmqtt.
J'essaye d'envoyer du json qui est généré dynamiquement par un scenario php.

Comme il n'est 'apparement' pas possible d'appeller directement une commande jmqtt avec son contenu json comme paramètre de commande ( why? ),  j'ai crée un virtuel contenant mon json , et jmqtt appelle cet objet pour envoyer cette valeur.

Sauf qu'il me rajoute des tremas "" en début et fin du json, et mon flux n'est pas parsé correctement par l'appareil qui reçoit la commande. Le json dans le virtuel ne comporte pas de "".

```
"{"id": 1, "state": "disabled", "time": "18:54:07", "days": [   "sunday",   "monday",   "tuesday",   "wednesday",   "thursday",   "friday",   "saturday" ] }" 
```
au lieu de: 
```
{"id": 1, "state": "disabled", "time": "18:54:07", "days": [   "sunday",   "monday",   "tuesday",   "wednesday",   "thursday",   "friday",   "saturday" ] }
```

Ce qui n'est pas le cas quand le json est directement renseigné comme valeur dans l'objet jmqtt. 

edit:
Dans le genre lié, mais à l'envers, si je stocke dans un virtuel une valeur de type "autre" contenant une chaine de charactères qui utilisent des nombres , par ex l'heure au format HH:ss , alors coté jmqtt il va supprimer les quotes si je genere le json directement dans le champs valeur jmqtt. Ce qui rend la valeur inutilisable car ce n'est pas un nombre.

Merci

**Comment by BadWolf42** [comment]
Bonjour KipK,

En quelle version de Jeedom et du plugin es-tu ?

Je pense comprendre le besoin. Mais peux-tu stp nous envoyer un peu plus de détail sur ce que tu est en train d'essayer de faire au cas où je ferai fausse route ? Notamment des captures du virtuel, du scenario et de l'équipement jMQTT et comment tu souhaiterais passer la valeur et sur quelle commande ?

> Sauf qu'il me rajoute des tremas "" en début et fin du json, et mon flux n'est pas parsé correctement par l'appareil qui reçoit la commande. Le json dans le virtuel ne comporte pas de "".

Oui, c'est un problème du Core Jeedom qui n'accepte pas ou alors de façon erratique le json. 
Il y a un certain nombre des discutions sur le sujet sur Commu : 
https://community.jeedom.com/t/bug-affichage-title-si-guillemets-presents/68123
https://community.jeedom.com/t/modifications-de-jeedom-evaluateexpression-bug/70303/12?u=bad
https://community.jeedom.com/t/wifilightv2-non-compatible-jeedom-4-2/77789/22?u=bad
https://community.jeedom.com/t/v4-2-ne-se-comporte-pas-comme-la-v4-1-avec-des-guillemets-dans-une-commande-action/77717/2?u=bad

Par contre, nous avons œuvré pour contourner le mieux possible ce problème, car MQTT s'appuie beaucoup sur le json.
Donc il est tout à fait possible avec jMQTT d'insérer un morceau de texte dans un json.
Il suffit d'utiliser une commande action de type Message, de cette façon :
![image](https://user-images.githubusercontent.com/8396512/182454892-6babf2f5-8e26-4c9c-96b2-bf93d0232651.png)(Payload `{"message":"#message#"}`)

Avec les commandes suivantes, on récupère bien le json formaté et une valeur en particulier :
![image](https://user-images.githubusercontent.com/8396512/182455530-f8b443b4-f0f3-4755-a018-2b0b611ba6e3.png)

Et voici l'équipement sur le dashboard :
![image](https://user-images.githubusercontent.com/8396512/182455297-012b69b4-fd24-45a6-a39b-cdf24ca44824.png)
(Le Titre est optionnel à l'affichage en configurant le widget de la commande)

Et depuis un scenario, tu peux appeler la commande avec ton message, de cette façon :
![image](https://user-images.githubusercontent.com/8396512/182456731-c2e940d7-3084-45ee-806f-bab149331e68.png)
![image](https://user-images.githubusercontent.com/8396512/182456671-ce0910a0-e4cb-4b38-811b-9f77d2a55369.png)
![image](https://user-images.githubusercontent.com/8396512/182456857-aa7be571-5c53-42af-8dc2-96ee13cbd4e6.png)

Ce test a été réalisé sur Jeedom 4.2.20, avec la dernière stable de jMQTT (`2022-07-25 01:01:17`).

Est-ce que ça correspond à ton besoin ?

Bad

**Comment by KipK** [comment]
j'ai aussi contourné le problème dans le meme genre en utilisant des simples quotes. La il ne me les vire pas une fois envoyé au mqtt ( dans le 2eme exemple ) .
Je me doutais bien que ca venait de jeedom, merci de m'avoir confirmé.

Sinon pendant qu'on est là :) et c'est lié car ca éviterais de s'embêter à contourner le problème. Pourquoi ne peut on pas envoyer notre payload directement en appelant l'objet jMQTT comme n'importe quel autre objet jeedom ?
Je sais que c'était aussi le cas sur le plugin MQTT et je me demande quelle en est la raison, car ca sort de l'ux jeedom.

**Comment by BadWolf42** [comment]
Bonjour,

> j'ai aussi contourné le problème dans le meme genre en utilisant des simples quotes

Attention, les simple quote ne sont pas des délimiteur de texte valides en json.

> Pourquoi ne peut on pas envoyer notre payload directement en appelant l'objet jMQTT comme n'importe quel autre objet jeedom ?

Peux-tu préciser, avec un exemple de ce que tu attends ?
 
> je me demande quelle en est la raison, car ca sort de l'ux jeedom.

Je ne comprends pas ton attente, quelle amélioration souhaiterais-tu que nous apportions ?
Quel comportement habituel de Jeedom manque dans jMQTT ? 

Bad

**Comment by KipK** [comment]
@badWolf42 yes, mais bonne nouvelle  Jeedom les remplace par des quotes une fois parsé, 
'#[Voiture][Charge VE][sched_time]#' donne bien : "20:17:00" par ex..

> Peux-tu préciser, avec un exemple de ce que tu attend

En gros, pour être raccord avec le reste de l'experience utilisateur, qu'on puisse affecter dynamiquement la valeur d'une commande en appelant la commande. Sans y passer par une variable #message# ( même si je te l'accorde le résultat est le même :), c'est juste que comme les virtuels et autre composants fonctionnent comme ça aussi  )
par ex: 
![jeedmqtt](https://user-images.githubusercontent.com/488789/182559050-59d72615-724a-4b49-b8a7-6bdb51a33910.jpg)


edit: dans mon visuel j'ai oublié de mettre le type en message.

**Comment by KipK** [comment]
D'ailleurs à juste titre, Jeedom devrait nous mettre à disposition un type "string" en plus de "message", histoire de pas avoir ce Titre qui ne sert à rien apparaitre sur l'UI, même si on peut le retirer coté widget.

**Comment by BadWolf42** [comment]
Hello @KipK,

> Jeedom devrait nous mettre à disposition un type "string" en plus de "message"

Pour ce besoin, c'est intimement lié à Jeedom, je t'invite à en discuter sur Community avec l'équipe Jeedom et, pourquoi pas, faire un PR sur le Core.

> qu'on puisse affecter dynamiquement la valeur d'une commande en appelant la commande

Si j'ai bien compris, tu fais référence au fonctionnement suivant du plugin Virtuel : avec une commande de type Action et sous type Message, le champ Valeur n'est pas pris en compte et le résultat est toujours "#title# #message#" ? Cf : 
https://github.com/jeedom/plugin-virtual/blob/beta/core/class/virtual.class.php#L382-L385

Je ne pense pas que ce soit souhaitable tel qu'implémenté dans Virtual.
Mais on peut adapter le fonctionnement de jMQTT pour y ressembler : dans le cas où le champ Valeur d'une commande Action est vide le tag du nom du type serait utilisé (slider -> `#slider#`, message -> `#message#`, etc) et type other -> ` ` (vide).

Qu'en penses-tu @Domochip ?

Bad

**Comment by KipK** [comment]
Oui, mais c'est très personnel. A vrai dire je me débrouille très bien en
l'état. Mais je me rappelle avoir buté à mes débuts de Jeedom il y a
plusieurs années avec le plugin de Lunarok sur ce point.

Par contre le bug évoqué tout en haut avec le json importé depuis un script
ou virtuel qui rajoute des trémas ça peut être problématique pour certains
use case.

**Comment by BadWolf42** [comment]
Hello @KipK,
La modification du comportement sur les payload vide est intégrée dans la Beta de demain :)
Bad

**Comment by KipK** [comment]
Ah super. Merci
