### ISSUE TITLE
template Osram Smart Plug +

### ISSUE THREAD

**Issue by chris777c** [BadWolf42/jMQTT#212]
Hello,

I would like to share my template for Osram Plug Smart+ see attachment 
[Osramplugsmartplus.TXT](https://github.com/Domochip/jMQTT/files/9422219/Osramplugsmartplus.TXT)

Best regard

**Comment by BadWolf42** [comment]
Hello,

Many thank for the template.
It has been integrated in the Beta that will be available tomorrow.

Bad
