### ISSUE TITLE
Icône du pluggin JMQTT en double dans Mes pluggins Jeedom

### ISSUE THREAD

**Issue by dandcs** [BadWolf42/jMQTT#214]
Bonjours,

Le problème constaté n'apporte pas de dysfonctionnement à JMQTT, il est juste visuel, Dans la section "Mes pluggins" de Jeedom, je retrouve en double l'accès au pluggin JMQTT, les deux permettent bien d'accèder à la configuration de JMQTT. 
Quelle action permettrait de ne retrouver qu'un seul icône ?

![Sélection_003](https://user-images.githubusercontent.com/84261847/192087726-60451f6d-dc6e-46f5-b071-ee006d82b671.png)

Merci pour vos retours.

**Comment by Domochip** [comment]
Désolé, mais cette partie n'est pas dans le périmètre de jMQTT.
Le mieux est de poster ce problème sur community.jeedom.com ou bien d'ouvrir un ticket de support auprès de Jeedom.
Le code qui gère l'installation d'un plugin est dans Jeedom Core

**Comment by dandcs** [comment]
Merci de votre retour rapide, en effet j'aurai dû avoir ce raisonnement, avant de vous solliciter. 


Merci encore. 

----- Mail original -----

De: "Domochip" ***@***.***> 
À: "Domochip/jMQTT" ***@***.***> 
Cc: "DanDCS" ***@***.***>, "Author" ***@***.***> 
Envoyé: Samedi 24 Septembre 2022 11:19:45 
Objet: Re: [Domochip/jMQTT] Icône du pluggin JMQTT en double dans Mes pluggins Jeedom (Issue #214) 



Désolé, mais cette partie n'est pas dans le périmètre de jMQTT. 
Le mieux est de poster ce problème sur community.jeedom.com ou bien d'ouvrir un ticket de support auprès de Jeedom. 
Le code qui gère l'installation d'un plugin est dans Jeedom Core

**Comment by Domochip** [comment]
pas de soucis :-)
