### ISSUE TITLE
Template Shelly_Bulb_Duo_RGBW.json

### ISSUE THREAD

**Issue by Jeandhom** [BadWolf42/jMQTT#226]
Bonjour bad,
J'ai fait quelques corrections sur certains payloads du template.
Je joins le nouveau template.
Merci.
[shellyColorBulbForum.json.txt](https://github.com/Domochip/jMQTT/files/9940659/shellyColorBulbForum.json.txt)

**Comment by BadWolf42** [comment]
Hello Jeandhom, ce sera pris en compte dans la prochaine béta

**Comment by Jeandhom** [comment]
Super.
Merci.
