### ISSUE TITLE
Impossible de publier une action depuis migration vers jMQTT github

### ISSUE THREAD

**Issue by Gis70** [BadWolf42/jMQTT#23]
Bonjour, 

Depuis que je viens de migrer vers jMQTT de Github il m'est impossible de publier depuis Jeedom, j'ai le message suivant : 
 `Publication échouée ( 5 : Error: The connection was refused.)`

Je reçois bien les topics

Ca fonctionnait juste avant.

Une idée ?

**Comment by foulek57** [comment]
Hello,

Tu as installer Mosquitto en local avec les dépendances du plugin ? 

Nicolas.

**Comment by Gis70** [comment]
Non j'ai un broker distant sur Docker, j'ai tenté une réinstalle des dépendances mais ça n'a rien changé, bouton Mosquitto local décoché du coup.

Edit : si je publie depuis mqtt explorer un set ON sur une prise ça marche bien, le pb vient du plugin sur jeedom

**Comment by Gis70** [comment]
l'user et le mdp du broker ne sont pas récupéré donc pas de login lors du publish, à vous de jouer pour trouver ce qui merde.

**Comment by foulek57** [comment]
Tu pourrais nous envoyer une capture d'écran de la configuration du broker ?

**Comment by Gis70** [comment]
yes j'ai pas eu le temps de rep ajd je regarde de suite.

**Comment by Gis70** [comment]
fix par #25 merci
