### ISSUE TITLE
feature request: option to null json properties when removed from topic

### ISSUE THREAD

**Issue by KipK** [BadWolf42/jMQTT#233]
Salut 
"Petite" feature request, 
pourrais t'on avoir la possibilité de null les propriétés d'un topic json si elle ne sont pas présentes dans la publication en cours. 

Use case: 
J'ai un topic json qui contient plus ou moins de propriétés selon les commandes. Je voudrais pouvoir savoir si cette props a été publiée ou pas, sinon j'affiche un autre resultat d'une autre variable.
Dans le comportement actuel si le topic ne contient pas la prop sur sa derniere publication, jmqtt renvoie la dernière valeur reçue.
Ce qui me pose un soucis car j'ai aucun moyen de savoir si cette valeur viens dêtre publiée ou pas. 

Un renvoie de "null" serait parfait :)

Coté conf, une checkbox sur le topic pour selectionner si on veut garder l'ancienne valeur ou la supprimer?

**Comment by BadWolf42** [comment]
Hello @KipK,

C'est une fonctionnalité de "niche" qui demande pas mal de changement dans jMQTT.
Si on l'implémente avec une checkbox (trop visible) cela risque de désorienter bon nombre d'utilisateurs.
Donc pas de garantie qu'on l'implémente.

Par contre, afin de bien cibler ce que tu souhaites, peux-tu stp nous donner :
- le payload json avec toutes ses clés,
- le payload json amputé de des clés qui ne sont pas toujours présentes,
- une capture d'écran des commandes info/action dans jMQTT ou autre que tu utilises,
- une capture d'écran du scenario (ou autre) où tu as besoin de traiter ces clés.

Merci,
Bad

**Comment by KipK** [comment]
je peux pas trop te montrer les scenarios / scripts car il y a un paquet de code ca risque de compliquer la chose.

Mais pour simplifier,, un des payloads ( ce cas se presente à l'ensemble des payloads json de cet appareil ( borne de recharge EV ) 
topic /claims
`{ "state": "active", "charge_current": 25, "max_current": 32, "auto_release": true }`
Chacune de ces propriétés peut etre presentes ou pas dans le "claim" et correspondent à des curseurs pour les param charge_current max_current, ou des widgets binaires pour state et auto_release.

Ce topic correspond à l'état actuel du chargeur.
 Il ne peut très bien contenir que :
`{ "state": "disabled" } `
ce qui signifie que les autres params ne sont pas reglés, et que le chargeur utilsie les valeurs par defaut ( la 2eme source d'infos que j'affiche en cas d'abscence de props )

**Comment by Domochip** [comment]
C'est un besoin bien trop rare pour être généralisé.
L'exemple est très intéressant. Est-ce que cela veut dire que les autres informations doivent être effacées si "state":"disabled" uniquement?

**Comment by KipK** [comment]
oui c'est bien mon probleme. 
Chaque json peut contenir n'importe laquelle de ces props, plusieurs, ou toutes à la fois ou pas du tout ( dans ce cas la le json contient {"msg": "no claims" }
Seule les props presentes corrsepondent à l'odre,, les autres justement doivent absolument avoir disparues, sinon impossible de connaitre avec exactitude l'ordre en cours.

**Comment by KipK** [comment]
Ca me semble pas si unique comme use case, la situation actuelle revient à envoyer un resultat qui n'est pas présent dans le topic  en cours :)

**Comment by Domochip** [comment]
Dans le post d'origine : 
> Je voudrais pouvoir savoir si cette props a été publiée ou pas, sinon j'affiche un autre resultat d'une autre variable.
Aurais-tu plus de détail sur cette finalité? C'est juste pour de l'affichage?

**Comment by KipK** [comment]
non c'est pour controler l'interface coté Jeedom de toutes ces fonctionalités. Par ex le slider "charge current" , va envoyer une demande d'ordre aux controleur sous la forme { "charge_current": 25 } , cet odre est enregistré dans ce qu'ils appelent un "claim" , qui correspond à l'ordre de mon client .
Ce claim peut etre complété par d'autres propriétés au fur et a mesure, ou des props peuvent etre retirés. 
Si toutes les props sont retirés, le claim en question renvoie un msg de type {msg: "empty"} 
Quand une prop est manquante, ou que le claim est vide, le slider va utiliser la valeur "max_current" renvoyé sur un autre topic qui correspond à la limite hardware max du controleur. 
A moins qu'un autre claim concurrent émis par un autre client est activé certaine propriété. Il y a une gestion des priorités dans ces differents claims qui permet de savoir quel est l'ordre prioritaire)

Peut être plus clair, un des topics , /claims//target , renvoie une structure Json avec deux objets: 
```
{
  properties: { 
    charge_current: 25,
    state: active,
    auto_release: true
  },
  {
  claims: {
      charge_current: 46524  // ID client qui a donné cet ordre 
      state: 46400                  // autre ID client qui a donné cet ordre
      auto_release: 46524
  }
}
```

Ce topic permet de savoir en un shot qui à ordonné quoi. Sauf qu'il ne contient que les props qui ont des ordres en cours. 
Si l'odre charge_current: 24 est enlevé, c'es tla valeur max de l'appareil ( 32A ) qui va etre prise en compte. 
Jeedom lui va en rester à 24 et penser qu'il y a toujours un odre du client 46524

**Comment by KipK** [comment]
Ça peut servir du coup aussi bien pour des valeurs à recuperer , dont l'affichage est conditionné par la présence de cette valeur ou pas , ou une commande qui va varier selon ( par ex pour revenir à la valeur 32A, si j'ai un client qui contrôle déjà un ordre équivalent je l'override en créant un nouveau "claim", si cet ordre vient de moi je le supprime pour revenir à la valeur par défaut. )

**Comment by KipK** [comment]
Tu vas trouver étrange que plusieurs client veuillent contrôler une même borne de charge. En fait les autres clients sont les différents services des fonctionnalités "smart" du contrôleur ( gestion de l'autoproduction solaire, délestage, agenda , OCPP,... )  ou d'un contrôle depuis l'UI, ou depuis Mqtt

**Comment by KipK** [comment]
Ça me permet par ex de faire des choses comme ça:
https://watch.screencastify.com/v/rfUevvOop9RcR79mJ7ud

( Je suis en train de refaire l'UI du contrôleur Open EVSE mais la j'utilise l'API http directement.  )
J'ai implémenté l'utilisation de cette api a travers mqtt , je voudrais pouvoir arriver à faire le même genre de chose sous Jeedom avec uniquement mqtt )

**Comment by Domochip** [comment]
Qu'est-ce qui pousse les JSON dont tu parles? Un OpenEVSE? quel modèle? quelle version?

**Comment by KipK** [comment]
Le module Wifi ( ESP32 ) de l'openevse, dans sa derniere version. 
https://github.com/OpenEVSE/ESP32_WiFi_V4.x

L'API HTTTP est ici:
https://openevse.stoplight.io/docs/openevse-wifi-v4/YXBpOjk5MTEz-open-evse-wi-fi-api

c'est le meme format de données pour les topics mqtt /claims et /override

**Comment by KipK** [comment]
C'est bizarre en fait, je suis quasi convaincu que ca marchaitcorrectement  avant. 
Dans mon jeedom j'avais un truc dans le genre pour la valeur affichée de max_current, et ca fonctionnait très bien:

#[MQTT][openevse][claim max_current]#?#[MQTT][openevse][claim max_current]#:32

Et depuis je ne sais plus quelle maj ca ne marche plus car il renvoie toujours l'ancienne valeur.

**Comment by KipK** [comment]
autre info interessante, cela semble marcher correctement avec une valeur de type info. 
J'ai une property "state" qui est soit active, soit disabled, soit pas definie 

Si le topic claims change sans la valeur state, j'ai bien state qui me renvoie null.

Ce n'est pas le cas avec les valeurs numerique qui gardent leur ancien etat.

**Comment by KipK** [comment]
Sinon je peux toujours renvoyer des etats nulls coté openevse sur mqtt, mais ca nous éloigne de l'api originale.

**Comment by BadWolf42** [comment]
> ca fonctionnait très bien:
> `#[MQTT][openevse][claim max_current]#?#[MQTT][openevse][claim max_current]#:32`

Je pense que tu devais faire ça dans un virtuel et pas dans jMQTT. Je ne pense pas que ça ait déjà fonctionné, car aucune valeur n'est envoyée vers la commande par jMQTT dans le cas où la propriété est inexistante. 

D'ailleurs un viruel intermédiaire est une bonne solution à ton problème, car nous ne pouvons pas modifier le comportement de jMQTT lorsqu'une propriété est manquante dans le json : certains équipements ne publient que ce qui a changé et pas tout le json.
En d'autres termes, si la propriété max_current n'est plus "juste", il faut qu'elle soit présente dans le json avec la bonne valeur.

**Comment by KipK** [comment]
Oui c'est la commande d'un virtuel.
Mais comment expliquer que cela fonctionnait correctement avant...
Je vais changer le code openevse pour l'adapter à cette contrainte et
publier les props vide .
Merci

**Comment by BadWolf42** [comment]
Comme évoqué, ce n'est pas à jMQTT de mettre à `null`, `""` (chaine vide) ou `0` les commandes associées à des propriétés manquantes dans le json, mais au programme qui publie le payload de définir les bonnes valeurs dans le json lors de la publication.
Je vais fermer cette issue.
