### ISSUE TITLE
Bug sur les icônes

### ISSUE THREAD

**Issue by Gis70** [BadWolf42/jMQTT#236]
Bonjour,

Depuis la maj d'octobre, j'ai un problème avec les icônes, dès que je le change il n'est pas prise en compte et affiche celui par défaut.

![image](https://user-images.githubusercontent.com/16589132/209435330-55397125-b7a9-477b-a6e3-2478259e799b.png)

**Comment by BadWolf42** [comment]
Bonjour,
Avez-vous testé la mise à jour d'aujourd'hui ?
C'est identifié et normalement corrigé dedans.
Bad

**Comment by Gis70** [comment]
oui justement c'est pour ça que je me permets une issue :-), j'ai effacé le cache du navigateur mais ça ne change rien.

si je clique sur un icône ça fonctionne, c'est après la sauvegarde que ça remet l'icône par défaut.

**Comment by BadWolf42** [comment]
Pour info, j'ai bien constaté que le problème est toujours présent. Je regarde pour corriger rapidement.
Peux tu me confirmer que tu es bien sur la dernière stable de Jeedom (4.3.12) ?

**Comment by BadWolf42** [comment]
Ce bug doit être (enfin) corrigé par le commit 1db366cd2a496abae9c1f30589903e6a703568e2.
La version stable de demain intégrera ce fix.

Si tu veux bien, tester et nous confirmer ça ici ?

Bad

**Comment by Gis70** [comment]
Bonjour, Dsl de la réponse tardive, je suis bien sur la dernière version de jeedom et la maj suite à ton commit a bien corrigé le problème, merci
