### ISSUE TITLE
template pour Prise Nous A1T with Tasmota firmware

### ISSUE THREAD

**Issue by vberder02** [BadWolf42/jMQTT#253]
J'ai ajouté un fichier de template dans le repo pour Prise Nous A1T with Tasmota firmware.

Pour info :
Il faut mettre le topic %topic%/%prefix%/ dans la config de la MQTT de l'interface de gestion de la prise.

Contenu du fichier :
`[REDACTED FOR LISIBILITY]`

Cf : https://github.com/vberder02/jMQTT/commit/ae449aa6a6820f2859efe693de9c793cd06a5538

**Comment by BadWolf42** [comment]
Hello @vberder02,

Merci pour ce template 👍 
J'ai retrouvé le fichier en question dans ton fork et modifié ton post pour plus de lisibilité.
J'intègre ça dès que possible 😉

**Comment by BadWolf42** [comment]
Hello @vberder02,

C'est mergé dans la prochaine beta avec le commit a4ae4c609f1d2363ae0d1979bd5c90d99f7a017d

Merci encore
