### ISSUE TITLE
Perte aléatoire du Client Broker

### ISSUE THREAD

**Issue by Balooforever** [BadWolf42/jMQTT#27]
Bonjour à tous,

Je rencontre un souci avec le broker JMQTT, il se coupe aléatoirement la nuit et les valeurs ne sont pas actualisé..

Niveau log j'ai le message suivant :
"exception thrown by MQTT client: Invalid function arguments provided."

Puis relance du demon dans 15 seconds mais cela boucle. Si je fais "redémarrer" sur mon client JMQTT, tout refonctionne.

Une idée ? Je peux lancer l'écoute en mode debug si besoin.

Configuration : 
- Mosquitto installé sur une instance Home Assistant
- JMQTT dernière version de ce repo

**Comment by foulek57** [comment]
Hello,
N'aurais tu pas deux sessions avec le même identifiant ?

**Comment by Domochip** [comment]
Bonjour,

Utilises-tu le plugin officel? Ou bien cette version?
![image](https://user-images.githubusercontent.com/33293764/113389650-afdcf800-9390-11eb-97a7-ae7c4f5fee53.png)

**Comment by Balooforever** [comment]
Bonjour,

J'utilise cette version, l'autre ne fonctionnait vraiment pas assez bien (d'ailleurs merci pour le boulot) mais je pense que foulek57 a identifié le problème, j'avais effectivement mon MQTT Explorer de lorsque je perds la connexion du Jeedom et j'utilisais le même identifiant mqtt..

Ca va me permettre de piloter mon chauffage :)

**Comment by Balooforever** [comment]
Finalement clôturé un peu vite, même avec un user dédié même souci ça a coupé cette nuit encore..

Actuellement il écoutait tout, je vais essayer de réduire le nombre de topic voir si c'est mieux.

**Comment by Domochip** [comment]
ok, 
Combien de broker as-tu?
Combien d'équipements?
L'erreur que tu recontres est un problème lié à la librairie MQTT utilisée (mosquitto-PHP).
Elle semble mal gérer le multithreading donc j'ai codé l'envoi en utilisant mosquitto_pub.
La librairie ne sert plus qu'à la réception.
Je pensais vraiment ne plus rencontrer cette erreur.

**Comment by Balooforever** [comment]
J ai un seul broker mais il est énorme (j'ai plus d'une centaine d'équipement :D)

Du coup j'ai supprimé la partie zwave qui ne me sert pas côté Jeedom, ça devrait mieux tourner :)

**Comment by Balooforever** [comment]
@Domochip J en profite (je n ouvre pas un autre bug), comment je peux envoyer une Action « true » dans un json ? Jeedom me le transforme en 1 a chaque fois et du coup échec de la command côté broker..

**Comment by BadWolf42** [comment]
Dit moi si ça fait l'affaire :
![image](https://user-images.githubusercontent.com/8396512/113483708-279c4700-94a5-11eb-98f5-a8550d46acc9.png)

**Comment by Balooforever** [comment]
Quand tu sauvegarde ça reste à « true » ?

car ma commande est plus complexe mais si je sauvegarde, il passe à 0/1

**Comment by Domochip** [comment]
@Balooforever Aurais-tu une ou deux captures d'écran?
C'est un problème que j'avais aperçu sur une issue coté Domotruc. 
Je l'avais mis dans les bugs à corriger dans un coin de ma tête. :-)
(Et vu que je suis à fond sur le JS en ce moment ...)

**Comment by Balooforever** [comment]
Bien sur :)
Par exemple, si je mets "true" à cet argument : 
![image](https://user-images.githubusercontent.com/48917118/113501586-8e157980-9526-11eb-9af9-ff3d8bcd1e7c.png)

Lorsque je sauvegarde : 
![image](https://user-images.githubusercontent.com/48917118/113501597-a9808480-9526-11eb-9b0c-d23287b463a1.png)

Pour la partie déconnexion du broker, en supprimant l'écoute sur tout les périphériques non utilisés (beaucoup trop de ligne ... :D), pas de plantage ce matin :)

**Comment by BadWolf42** [comment]
@Balooforever, je viens de vérifier et oui, seuls true/false restent après sauvegarde.
Par contre dans une structure JSON, ils sont interprétés à la sauvegarde.

@Domochip, un autre comportement rigolo, mais certainement lié au Core :
Si je créee 2 commandes Bind / Unbind de type action/message
![image](https://user-images.githubusercontent.com/8396512/113502943-54953c00-952f-11eb-8a12-b33cc278a860.png)
Et que je les utilise dans un scenario
![image](https://user-images.githubusercontent.com/8396512/113502921-43e4c600-952f-11eb-875b-53c318a8de0d.png)
Si je mets les "{" "}" dans le scenario, après sauvegarde le champ message du scenario devient "Array" au lieu du json

Mais en l'occurrence, je pense que des tickets différents sont appropriés

**Comment by Domochip** [comment]
J'ai fait des recherches hier soir sur ce sujet.
C'est bien un problème du Core.
Ca impacte tous les plugins.
J'ai ouvert un sujet sur Community.
J'attend un petit peu pour voir si on a un retour, mais sinon, il faudra que je code un truc pour palier à ce comportement.

https://community.jeedom.com/t/json-interprete-dans-champs-des-commandes-bug-core/57935

**Comment by Balooforever** [comment]
Il manque presque un type « json » non interprété par le Core en fait.

Enfin bon, j arrive tout de même à m en dépatouiller, merci vraiment pour le travail !

**Comment by Domochip** [comment]
Pour le bug des booléens transformés (true qui devient "1"), J'ai soumis la PR pour corriger au core.
Ca corrigera le soucis pour tous les plugins.
https://github.com/jeedom/core/pull/1825
