### ISSUE TITLE
JMQTT don't like : in json path, I think ?

### ISSUE THREAD

**Issue by chris777c** [BadWolf42/jMQTT#316]
Hello,

I updated my shelly plus 1 pm  with last version V1.1 and I meet one difficulty for get information send by this, I can't arrive to bind into alone commands.

This is JSON send on path :
shellies/shellyplus1pm-XXX/events/rpc

`{"src":"shellyplus1pm-XXX","dst":"shellies/shellyplus1pm-XXX/events","method":"NotifyStatus","params":{"ts":1707639094.27,"switch:0":{"id":0,"current":0.683}}}`

and again

`{"src":"shellyplus1pm-XXX","dst":"shellies/shellyplus1pm-XXX/events","method":"NotifyStatus","params":{"ts":1707639600.27,"switch:0":{"id":0,"aenergy":{"by_minute":[2382.607,2620.038,2361.400],"minute_ts":1707639599,"total":13060.705}}}}`

I try get command info "current" so I write : 
[example_2](https://community.jeedom.com/uploads/default/original/3X/2/9/2964dc19f0a0aafc5daa82d7aa576d20ae4c820d.png)

But no information up to me, I try this to by automatic suggestion  :

[example_1](https://community.jeedom.com/uploads/default/original/3X/2/9/2964dc19f0a0aafc5daa82d7aa576d20ae4c820d.png)

I think jmqtt don't like switch:0

**Comment by BadWolf42** [comment]
Hi @chris777c,

I don't think this there is an issue with `:` in jsonPath as long as it is enclosed in `"`.

Please continue investigation on the Community thread: 
https://community.jeedom.com/t/shelly-1-plus-pm-recuperer-info-suite-maj-dernier-firmware/120945/

Bad
