### ISSUE TITLE
Ajout icônes d'équipement

### ISSUE THREAD

**Issue by Jeandhom** [BadWolf42/jMQTT#318]
Hello Bad,

Peux tu ajouter deux icônes d'équipement ?

Afficheur (ex Awtrix)
Pompe (ex Pompe vide cave)

Merci.

**Comment by BadWolf42** [comment]
Hello @Jeandhom,

Est ce que ce type d'icones te conviendrait :
![image](https://github.com/BadWolf42/jMQTT/assets/8396512/fdf7bded-59a8-4686-9d2c-81a44874bd22)
&
![image](https://github.com/BadWolf42/jMQTT/assets/8396512/a71c7ef3-d531-40b5-aa98-fa10fec8e646)

Evidement à retravailler avec le jaune de jMQTT ;)

Bad

**Comment by Jeandhom** [comment]
Merci Bad pour ta prise en compte.
Je n'ai pas d'avis, tu fais au mieux et au plus facile pour toi.
L'important est d'avoir ces types d'équipement supplémentaires.

**Comment by BadWolf42** [comment]
Le commit https://github.com/BadWolf42/jMQTT/commit/9360402f967272b65ce7d8920a183af5251ef5f7 intègrera les icones, lorsqu'il passera en beta

**Comment by Jeandhom** [comment]
Super,
Je clôture.
