### ISSUE TITLE
Erreur suite à relance des dépendances

### ISSUE THREAD

**Issue by Mick20553** [BadWolf42/jMQTT#321]
Bonjour, 
J'ai déjà signalé cette erreur dans la communauté Jeedom, et on m'a répondu qu'il fallait passer de debian 10 à debian 11, car je risque d'avoir des problèmes avec certain pluguin si je ne fais pas cette mise à jour dans moins d'un mois.

> Vous devez suivre la procédure pour migrer la box atlas vers debian11 (reset usine) sans cela plus aucun plugin ne fonctionnera à terme, vous êtes sur un système qui sera obsolète dans moins d’un mois.

Aussi, je trouve regrettable que Jeedom ne prévienne pas les clients de cette obsolescence et j'aimerais avoir une réponse officielle à ce problème et une procédure claire qui me permet de corriger mon système avant qu'il devienne obsoleète? Je rappelle que je ne suis pas un expert informatique et que je suis un simple utilisateur avec quelques notions.
Rappel du problème et log de jMQTTdep:
```
================================================================================
== Jeedom 4.4.6 Atlas in Debian GNU/Linux 10 (buster) on aarch64/arm64/64bits
== Python 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
== jMQTT v23.11.7 (2024-05-17 13:03:17) branch:stable previously:v23.11.6
======================================================================
== 03/06/2024 20:22:00 == Dependencies installation for jMQTT
======================================================================
[  0% ] : Synchronize the package index...
[  9% ] : Synchronize the package index :  ERROR 
[ 10% ] : Purge dynamic contents...
[ 19% ] : Purge dynamic contents : [  OK  ]
[ 20% ] : Install Composer...
[ 29% ] : Install Composer : [  OK  ]
[ 30% ] : Install JsonPath-PHP library...
[ 39% ] : Install JsonPath-PHP library : [  OK  ]
[ 40% ] : Remove Composer...
[ 49% ] : Remove Composer : [  OK  ]
[ 50% ] : Install python3 venv and pip debian packages...
[ 59% ] : Install python3 venv and pip debian packages : [  OK  ]
[ 60% ] : Create a python3 Virtual Environment...
[ 69% ] : Create a python3 Virtual Environment : [  OK  ]
[ 70% ] : Install required python3 libraries in venv...
[ 99% ] : Install required python3 libraries in venv : [  OK  ]
[100% ] : Finished !
======================================================================
==KO== Installation Error
======================================================================
== ANALYSING ERRORS...
== NO KNOWN ERROR DETECTED
== Error in step : Synchronize the package index
== Line 13
== Command `sudo apt-get update' have an issue
== Return code is 100
== Error message :
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Ign:4 http://deb.debian.org/debian buster-backports InRelease
Err:5 http://deb.debian.org/debian buster-backports Release
404  Not Found [IP: 2a04:4e42:6a::644 80]
Hit:6 http://mirrors.xtom.de/armbian buster InRelease
Hit:7 https://deb.nodesource.com/node_18.x buster InRelease
Reading package lists...
E: The repository 'http://deb.debian.org/debian buster-backports Release' no longer has a Release file.
======================================================================

**Comment by Mick20553** [comment]
Je viens de recevoir une nouvelle version de jMQTT du 8/06/2024, et je viens de la charger. A ma grande surprise le problème de dépendance semble résolu , car il n' ya plus d'erreurs? et ceci sans être passé en debian11. Aussi, pouvez vous me confirmer la necessité impérative de passer en debian 11.
Cordialement

**Comment by BadWolf42** [comment]
Oui, c'est évoqué dans le changelog : il y avait un problème sur la bibliothèque qui gère les dépendances.

Non, pour jMQTT il n'est pas obligatoire de passer en Debian 11, jMQTT est compatible avec Debian 9, 10, 11 et 12.

**Comment by Mick20553** [comment]
Merci pour votre retour et la correction efficace.
Par contre je comprends que pour jMQTT il n’y a pas de problème avec la version Debian 10, par contre d’après le forum je comprends qu' il risque d'y avoir problème avec d’autres plugins ( A définir?)
Cordialement
Michel

**Comment by BadWolf42** [comment]
Mais de rien 😊

> je comprends que pour jMQTT il n’y a pas de problème avec la version Debian 10, par contre d’après le forum je comprends qu' il risque d'y avoir problème avec d’autres plugins ( A définir?)

En effet, certains plugins évoluent et leurs développeurs ne souhaitent plus maintenir la compatibilité avec Debian 10, et certains ne sont plus compatibles avec Debian 9 depuis longtemps. Ca demande beaucoup de temps et d'énergie de s'assurer de la compatibilité. Aujourd'hui, Jeedom et ses plugins doivent pouvoir s'executer sur Debian 10 ET 11, mais la prochaine version (v4.5) changera peut-être ça.

A noter que cet outil de ticket/support est dédié à jMQTT, je ne peux pas vous répondre pour autre chose que jMQTT. 
Pour avoir du support ou des réponses aux questions concernant le Core, il est préférable d'ouvrir un ticket chez Jeedom. 
Et pour avoir du support ou des réponses concernant les autres plugins, il faut contacter le développeur du plugin en question.

Bonne journée,
Bad

**Comment by Mick20553** [comment]
Merci encore pour votre transparence et pour votre aide
Cordialement 
Michel
Envoyé de mon iPhone
