### ISSUE TITLE
SPEED Improvement breaks new command add

### ISSUE THREAD

**Issue by BadWolf42** [BadWolf42/jMQTT#35]
### Description
When adding at least an info command AND an action command, all the newly added command type switch to the last selected type.
When adding multiple action commands, top added action command has multiple times the same value in list "Valeur par défaut de la commande".

### Issue reproduction
New Infos become Action : https://www.awesomescreenshot.com/video/3420006?key=0a72d40ff9ec6a06a5b046ba6cd2d044
New Actions become Info : https://www.awesomescreenshot.com/video/3420015?key=69667720ec59ce6b4e9e737861d0dcf6
Multiple ref values : https://www.awesomescreenshot.com/video/3420044?key=bc9585bca1a4923c9a61bae44d8f9286

### Issue location
Around:
https://github.com/Domochip/jMQTT/blob/656a3b81911a084d647b0d5e66fb6a96e8085d37/desktop/js/jMQTT.js#L661
https://github.com/Domochip/jMQTT/blob/656a3b81911a084d647b0d5e66fb6a96e8085d37/desktop/js/jMQTT.js#L739
https://github.com/Domochip/jMQTT/blob/656a3b81911a084d647b0d5e66fb6a96e8085d37/desktop/js/jMQTT.js#L743
https://github.com/Domochip/jMQTT/blob/656a3b81911a084d647b0d5e66fb6a96e8085d37/desktop/js/jMQTT.js#L804

**Comment by foulek57** [comment]
Thank you very much for the detailed issue !
Fixed see commit https://github.com/Domochip/jMQTT/commit/544ec1019d4db26e07754ac1f5270ef9b4671ef7
