### ISSUE TITLE
Unprotected logfile rename

### ISSUE THREAD

**Issue by BadWolf42** [BadWolf42/jMQTT#36]
As per the following error log :
```
[Sat Apr 17 17:11:53.999505 2021] [php7:warn] [pid 26770] [client 192.168.xx.xx:53826] PHP Warning:  rename(/var/www/html/core/class/../../log/jMQTT_test,/var/www/html/core/class/../../log/jMQTT_dummy): No such file or directory in /var/www/html/plugins/jMQTT/core/class/jMQTT.class.php on line 457, referer: https://jeedom.xx.xx/index.php?v=d&m=jMQTT&p=jMQTT&id=632
```

Code here fails to check if logfile exists before renaming:
https://github.com/Domochip/jMQTT/blob/bb5a33579435aeb1490d933bbb1173bf0b0d000b/core/class/jMQTT.class.php#L457

**Comment by Domochip** [comment]
Can we close this issue?
Do you confirm your PR solves definitely this issue?

**Comment by BadWolf42** [comment]
I do, you can close this issue.
