### ISSUE TITLE
Last communication date is too aggressively updated

### ISSUE THREAD

**Issue by BadWolf42** [BadWolf42/jMQTT#38]
### Description
"Last communication date" is updated on an empty equipment when disabled, then enabled, even if no topic is subscribed, no command exists or no value is updated.

### Reproduction
https://www.awesomescreenshot.com/video/3420884?key=c3187e612062cbc709626c25adf58c1a

**Comment by foulek57** [comment]
Thanks !

The last communication date are update from core by setIsEnable function.
`if ($_isEnable) {
				$this->setStatus(array('lastCommunication' => date('Y-m-d H:i:s'), 'timeout' => 0));
			}`
