### ISSUE TITLE
Delete template

### ISSUE THREAD

**Issue by guldnerthomas** [BadWolf42/jMQTT#42]
Hi,

Is there a solution to remove a template in jMQTT?

**Comment by Domochip** [comment]
Not yet, except by going into jeedom folders and remove the file (/var/www/html/plugins/jMQTT/core/config/template)
It's planned to add a template "manager"

**Comment by djo28** [comment]
Il faudrait également pouvoir réenregistrer un template car en en créant un avec le même nom, il y en a du coup deux.

**Comment by BadWolf42** [comment]
Hi @djo28,

This issue should be addressed by PR #112.
We will tell you when it is released in beta/stable.

Bad

**Comment by BadWolf42** [comment]
Hi @djo28,
Template Manager will be available in tomorrow beta
Cheers

**Comment by Domochip** [comment]
available in current beta :-)

**Comment by djo28** [comment]
Works very well, thanks. Is there any plan to put the templates in common through the community ?

**Comment by Domochip** [comment]
there is no specific "market" planned.
People can submit their template through PR or issue here to be integrated

**Comment by BadWolf42** [comment]
Hello @guldnerthomas ,
As Template Maanger has been merge in stable, I will close this issue.
We are looking in a way to ease the template sharing (by automating issue/PR creation).
