### ISSUE TITLE
High CPU consumption. Crontab process

### ISSUE THREAD

**Issue by pirracas77** [BadWolf42/jMQTT#43]
Hello:

I have realized that the crontab process for jmqtt is consuming a lot of CPU frequently. (92% in the example below)

`~$ top  
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 2486 www-data  20   0  646428 446104  29780 R  92,8  22,0 390:32.03 php`

`~$ ps -ef |grep 2486
www-data  2486     1 26 abr24 ?        06:31:11 php /var/www/html/core/class/../php/jeeCron.php cron_id=42179`

![image](https://user-images.githubusercontent.com/18216098/116001885-2ae3a800-a5f7-11eb-957d-1f6f70761d69.png)

This implies that jmqtt plugin sometimes gets stuck in actions as simple as "duplicating a equipment" and I forced to reboot the whole debian system to have the daemon up and runing again.

**Comment by Domochip** [comment]
The daemon mechanism of jMQTT is under complete rewriting (Python + Websocket daemon).
What's your version of Jeedom (the end of you screenshot indicates "En curso")...

**Comment by pirracas77** [comment]
My version is 4.1.22.
I would like to add that I cannot stop/start the daemon from the plugin once it starts to be in troubles

**Comment by foulek57** [comment]
Can you send the logs in debug please ?

**Comment by pirracas77** [comment]
Thanks for your support.

This is the log section when I try for example to remove one equpment

`[2021-04-26 09:36:06][INFO] : removing equipment homeassistant
[2021-04-26 09:36:06][INFO] : relance le démon
[2021-04-26 09:36:06][INFO] : arrête le démon`


The broker is down and I cannot re-start again from this point. I have to reboot debian to start it again.

**Comment by pirracas77** [comment]
Not always but frecuently the problem arises in the same situation.
Yes, I have the logs in debug mode, but unfortunately nothing interesting is showing in it.

**Comment by pirracas77** [comment]
I think I found a workaround.
I have deactivated the option "Ajout automatique des commandes" in the broker.
Now the CPU consumption is reasonable and the daemon restart correctly when you delete an equipment.
I really don't know if it is a real workaround or just coincidence.
Anyway I will keep my eyes on it.

**Comment by Domochip** [comment]
What version do you use?
Master, beta or new_daemon one?

**Comment by pirracas77** [comment]
Currently I am on Master. Just updated this morning after my previous comment.

**Comment by Domochip** [comment]
Sorry, effort is focused on beta version now which includes a completely different daemon...
I'm not the author of the previous daemon and don't know it deeply.

**Comment by pirracas77** [comment]
> Sorry, effort is focused on beta version now which includes a completely different daemon...
> I'm not the author of the previous daemon and don't know it deeply.

No problem. I will try the beta version tomorrow again. But this time directly from the market. ;)
Congrats!
