### ISSUE TITLE
Package: make

### ISSUE THREAD

**Issue by fnoir** [BadWolf42/jMQTT#45]
Hi,

Can you add "make" package on step "Install dependancies" ?

Error during installation:

```
running: make
sh: 1: make: not found
ERROR: `make' failed
```

**Comment by Domochip** [comment]
A new daemon is currently in test (new_daemon branch) which doesn't require anymore make :-)

**Comment by Domochip** [comment]
Using a standard debian and Jeedom install, "make" is available.
How did you install your Jeedom?

**Comment by fnoir** [comment]
I use a minimal debian for Jeedom.

"make" is available but isn't installed with Jeedom dependencies.

**Comment by Domochip** [comment]
Arf, I think "make" is installed on my debian by some other packages...
I'm focused on beta version which have a new daemon and new dependancies which doesn't need "make" anymore.

**Comment by Domochip** [comment]
make requirement will be removed on next version
