### ISSUE TITLE
New beta version uninstall mosquitto-clients

### ISSUE THREAD

**Issue by pirracas77** [BadWolf42/jMQTT#54]
Hello:

I have installed from the market the new beta_version.
I realised that  the packet mosquitto-clients is not present after the installation in my Debian.

could you check?

**Comment by Domochip** [comment]
yes, it is removed during the upgrade process, otherwise the dependancy check of the previous plugin save a good dependancy status.
Subsequent update won't remove it.
You're using it for something else?

**Comment by pirracas77** [comment]
> yes, it is removed during the upgrade process, otherwise the dependancy check of the previous plugin save a good dependancy status.
> Subsequent update won't remove it.
> You're using it for something else?

Yes, I use it. I have my owns developments (shell scripts)  that runs in the same Debian that send mqtt information to jeedom via mosquitto.
