### ISSUE TITLE
BETA - Deleted Daemon logfile does not respown

### ISSUE THREAD

**Issue by BadWolf42** [BadWolf42/jMQTT#66]
If jMQTT_daemon logfile is delete, new incomming debug logs will be lost.

Rework should be done on python logging:
https://github.com/Domochip/jMQTT/blob/a184a8a068516c737299b5231e61b4fa78a1ef34/resources/jmqttd/jmqttd.py#L437

Ref:
https://github.com/Domochip/jMQTT/blob/a184a8a068516c737299b5231e61b4fa78a1ef34/resources/jmqttd/jeedom/jeedom.py#L159-L161

**Comment by BadWolf42** [comment]
Ok, issue is here:
https://github.com/Domochip/jMQTT/blob/660d290a066fc8b56e6ca1dd59e95cd5f8607947/core/class/jMQTTBase.class.php#L155

A redirection to a file, survives the deletion of the file, and logs are still going to the "deleted" file.
The so-called file is only a pointer to the real storage space that continues to exist until it is closed by the process holding it.
Ref : https://stackoverflow.com/questions/25711921/deleted-the-file-where-output-is-still-being-redirected

There is no way (that I could think) that we could detect the file has been deleted and should be recreated and re-mapped.

2 option here:
1. We accept the way it works, it is the same for all plugin that I could check
2. We replace the redirection by a "logfile" parameter, that logging will be done from inside the daemon, not outside.

I suggest option 1 and close this issue.

**Comment by Domochip** [comment]
OK for the option 1.
There is no strong needs about this
