### ISSUE TITLE
BETA - Allow customization of keepalive interval

### ISSUE THREAD

**Issue by AlexpFr** [BadWolf42/jMQTT#77]
Allow customization of keepalive interval in connect function.

`connect(host, port=1883, keepalive=60, bind_address="")`

**Comment by Domochip** [comment]
Hi, What's the use case?

**Comment by AlexpFr** [comment]
Limit billable traffic on publics clouds.

**Comment by Domochip** [comment]
What provider bill keepalive traffic?!

**Comment by AlexpFr** [comment]
[https://cloud.google.com/iot/pricing](https://cloud.google.com/iot/pricing)
![image](https://user-images.githubusercontent.com/62973006/118355128-cc16ac00-b56e-11eb-8deb-2e185d91ffeb.png)

it is infrequent use. If you don't want to complicate the Broker configuration interface, I will understand.

**Comment by Domochip** [comment]
![image](https://user-images.githubusercontent.com/33293764/118355197-1730bf00-b56f-11eb-93c6-c80997be7259.png)
1. It's billed only if you reach 250MB per month
2. PINGREQ are sent only if you don't send any other message within the keepalive time (60sec)

Are you in this case? send over 250MB/month AND having more than 60sec without sending data?
(Even if you're connected and doesn't send anything, it needs a packet every 10sec to reach 250MB/month)

**Comment by AlexpFr** [comment]
Indeed I had not seen that we had so much margin.
It may not be necessary to overload the configuration page. 

You can close this issue if you want.
