### ISSUE TITLE
Action before info using same topic => wrong JSON view

### ISSUE THREAD

**Issue by Domochip** [BadWolf42/jMQTT#84]
If an action cmd is placed before an info cmd using the same topic, the JSON view is incorrect : 

In Classic Mode:
![image](https://user-images.githubusercontent.com/33293764/118820119-440a0c80-b8b6-11eb-9fc3-174130371ff2.png)

In JSON Mode:
![image](https://user-images.githubusercontent.com/33293764/118820384-829fc700-b8b6-11eb-8027-fc6274c3321e.png)

**Comment by BadWolf42** [comment]
Still reproducible on current beta (https://github.com/Domochip/jMQTT/commit/34614106c81038066d68e93493d5aeb39c345700)

**Comment by BadWolf42** [comment]
Cannot be reproduced since commit [1241d9c](https://github.com/Domochip/jMQTT/commit/1241d9c3bbde0d56c62528f97eb65c8e4637d454) with Jeedom 4.2.13
