### ISSUE TITLE
on_mqtt_message raised an Exception

### ISSUE THREAD

**Issue by pirracas77** [BadWolf42/jMQTT#89]
Hello,

Not sure if this issue was reported before.
I have this issue after sending a "get" mqtt message

<html>
<body>

2021-06-30 10:09:56 | jMQTT | on_mqtt_message raised an Exception : [MySQL] Error code : 23000 (1062). Duplicate entry '422-get' for key 'unique' : INSERT INTO `cmd` SET `id` = :id, `logicalId` = :logicalId, `generic_type` = :generic_type, `eqType` = :eqType, `name` = :name, `order` = :order, `type` = :type, `subType` = :subType, `eqLogic_id` = :eqLogic_id, `isHistorized` = :isHistorized, `unite` = :unite, `configuration` = :configuration, `template` = :template, `display` = :display, `value` = :value, `isVisible` = :isVisible, `alert` = :alert
-- | -- | --

</body>
</html>

![image](https://user-images.githubusercontent.com/18216098/123927121-d2c97900-d98c-11eb-9a99-170e26cf03a9.png)

This is the device

https://www.zigbee2mqtt.io/devices/SM-AZ713.html#useelink-sm-az713

**Comment by Domochip** [comment]
What jMQTT version do you use: stable or beta?

**Comment by pirracas77** [comment]
I use the beta. Recently updated indeed.

**Comment by Domochip** [comment]
Do you have this error each time you send the "get" message?

**Comment by pirracas77** [comment]
> Do you have this error each time you send the "get" message?

Sorry for the delay.

Yes, every time.

`
<html>
<body>


2021-07-15 08:28:10 | jMQTT | on_mqtt_message raised an Exception : [MySQL] Error code : 23000 (1062). Duplicate entry '422-get' for key 'unique' : INSERT INTO `cmd` SET `id` = :id, `logicalId` = :logicalId, `generic_type` = :generic_type, `eqType` = :eqType, `name` = :name, `order` = :order, `type` = :type, `subType` = :subType, `eqLogic_id` = :eqLogic_id, `isHistorized` = :isHistorized, `unite` = :unite, `configuration` = :configuration, `template` = :template, `display` = :display, `value` = :value, `isVisible` = :isVisible, `alert` = :alert
-- | -- | --



</body>
</html>`

**Comment by BadWolf42** [comment]
Hello @pirracas77, do you still experience this issue?
Did you try to re-create the faulty device?

**Comment by pirracas77** [comment]
> Hello @pirracas77, do you still experience this issue?
> Did you try to re-create the faulty device?

Yes, it still happens.

But I understood today what happend:

if you send this type action command 

![image](https://user-images.githubusercontent.com/18216098/132466011-0d15bbbd-f1a0-4d70-8b93-d9dad0e2768b.png)

JMQTT immediatilly recives a command of type info when the new message arrives at the topic and tries to add it. As the name is the same as the action command, it crasses

The workaround is to name the action command different from the info command ("got" instead of "get" in the example below).
The info command is auto created without problems this time.

![image](https://user-images.githubusercontent.com/18216098/132466508-906aac14-5860-4bb9-9f37-1ca63b292393.png)

![image](https://user-images.githubusercontent.com/18216098/132466215-8ec28b7e-c291-4fc7-a894-3340a35501d2.png)

**Comment by BadWolf42** [comment]
Hello, thank you for your reply.

I'm not sure to understand, did you have 2 commands "get" on the same equipment (one info, the other action) ?
This should not be possible...

**Comment by pirracas77** [comment]
> Hello, thank you for your reply.
> 
> I'm not sure to understand, did you have 2 commands "get" on the same equipment (one info, the other action) ?
> This should not be possible...

No. I dont have 2 commands. (not initially)

The command type info is created authomatically by JMQTT as it is listening in the same topic when you lauch the commant type action.

**Comment by BadWolf42** [comment]
EDIT : New devious behaviors discovered while fixing...

Ok, I confirm I can reproduce, following those steps:

Create a new equipment subscribing at least topic "irrelevant/topicname"
Ensure that "Automatically add new commands" IS ENABLED
Create a new command "action" with name "topicname" for topic "irrelevant/topicname" (value is not important)
OR Create a new command with name "topicname", type and topic is not relevant
Enable the equipment and Save
When a message is received on topic "irrelevant/topicname", jMQTT tries to create a new command "info" using name "topicname" for topic "irrelevant/topicname", which is in collision with existing command "action".
Implying the recurrent error.

Thank you so much for helping us catching this tricky bug!

**Comment by BadWolf42** [comment]
Fix will be available soon, see PR #98.

**Comment by Domochip** [comment]
@pirracas77, do you still encounter the issue?

**Comment by pirracas77** [comment]
> @pirracas77, do you still encounter the issue?

It is OK for me.

**Comment by pirracas77** [comment]
Good job guys!

**Comment by Domochip** [comment]
@BadWolf42 power!!!
