### ISSUE TITLE
Value not fetched or not updated in an info command when added manually

### ISSUE THREAD

**Issue by msannier** [BadWolf42/jMQTT#90]
Context (early July '21):
1) Jeedom 4.1.23 on Raspbian Buster with latest jMQTT plugin from the Marketplace
2) Mosquitto installed on another machine than Jeedom
3) MQTT Explorer used on a third machine to monitor topic values of the Mosquitto server
Use case:
Manually add an equipment without automatic command discovery.
Then add a manual info command that read a topic and a manual action command that updates its value.
Use the Test button in the info command to fetch the value.
Symptom:
No value is fetched or the value is fetched but never updated again, whatever the topic's value is in MQTT Explorer.
Notes:
- The action command is correctly working, showing that the communication with the broker is OK
- The same use case with the MQTT plugin (from lunarok) is working.

**Comment by Domochip** [comment]
What version do you use : stable or beta?

**Comment by msannier** [comment]
Stable

**Comment by Domochip** [comment]
The MQTT message dispatch logic has been rewriten in **beta** (and the complete daemon too) to fix this.

**Comment by msannier** [comment]
I installed the beta branch, which requires to manually launch the installation of dependencies.
It automatically added 1 (only) of the sub-topic with a value of “1”, whereas the real value was different.
But when updating the value on the broker the plugin correctly then reflected the value through the info command’s test button.
So this is working better than the ‘stable’ version.

But, none of the other subtopics were automatically detected and furthermore when I manually added some of these, the test command did not fetch the values.

Additional information on the context:
Topics are:
Hosing/EV/EV1, Hosing/EV/EV2, Hosing/EV/EV3, Hosing/EV/EV4, Hosing/EV/EV5, Hosing/EV/EV6, Hosing/EV/EV7, Hosing/EV/EV8.

Should I open another issue?

Screenshots of configuration & log are attached.
[jMQTT_MyIoTserver.log](https://github.com/Domochip/jMQTT/files/6763484/jMQTT_MyIoTserver.log)
<img width="1252" alt="EquipmentConf" src="https://user-images.githubusercontent.com/24368883/124457226-da718f00-dd8b-11eb-9a55-0f6b0e2bafc6.png">
<img width="1252" alt="InfoCommands" src="https://user-images.githubusercontent.com/24368883/124457235-dc3b5280-dd8b-11eb-9e77-50cf62d73164.png">
<img width="559" alt="jMQTTplugin-objects" src="https://user-images.githubusercontent.com/24368883/124457240-dcd3e900-dd8b-11eb-8ac4-143e2e527d6c.png">
<img width="447" alt="MQTTtopics" src="https://user-images.githubusercontent.com/24368883/124457242-dd6c7f80-dd8b-11eb-9b0b-7331a3d7a4b9.png">

**Comment by Domochip** [comment]
What happens if you click on "test" button on the right, do you get the value.
I think there is a display/refresh problem only but message are correctly parsed and dispatched

**Comment by msannier** [comment]
When I restart Jeedom:
1 - If I click on “Test” on first (automatically created) information command, I get a “Command result: 1” (this is incorrect; the real value is 7, as shown in the attached snapshot).
2 - If I click on “Test” on the second and third (manually created) information command, I get a “Command result:” (i.e. empty).

So there are several possible display problems as the initial fetching of the value (for first information command) always shows a “1”, whatever the backend value at the broker’s, and others show no value.

If this is working as design, what is your recommended way to check the value elsewhere in Jeedom?

<img width="949" alt="DifferentValues" src="https://user-images.githubusercontent.com/24368883/124468398-545c4500-dd99-11eb-89eb-439d278ce0c5.png">

**Comment by Domochip** [comment]
What I understand is that automatically created command contains a wrong value until a new one is published. right?

**Comment by msannier** [comment]
Correct, that is the first issue, and this happens again each time Jeedom has just restarted.

**Comment by msannier** [comment]
Update.
For the above Hosing/EV/EV2 and Hosing/EV/EV3, despite no value being shown at Jeedom's startup, the value is refreshed if one is published to the MQTT broker. So it seems that it is the same behavior for all topics when all have been refreshed by publishers and only the behavior at startup is varying: "1" is always put in first manually created command's value and nothing in next of such commands.

**Comment by BadWolf42** [comment]
Hi @msannier, if you need the last published value, on a specific topic, to be fetched at jMQTT startup, I suggest you put the retain flag when value is published by the device. Otherwise, only the newly published value will be received.
So, it seems to work as intended.

If you get parasite/wrong value on jMQTT startup, maybe you have set the retain flag on an old message, that is now sent to jMQTT on connection before another value is received from the device. 

Could you please check?

**Comment by msannier** [comment]
Hi @BadWolf42. Setting the retain flag make it work correctly. Whether the topic has changed or not changed, the info command now displays the correct topic version at startup. I'm closing this issue. Thanks.
