### ISSUE TITLE
Last Beta : Unable to load dynamic library 'mosquitto.so'

### ISSUE THREAD

**Issue by Gis70** [BadWolf42/jMQTT#92]
Bonjour, 

J'avais sauté qq maj en BETA et depuis la dernière j'ai ça dans les logs: 

`PHP Warning:  PHP Startup: Unable to load dynamic library 'mosquitto.so' (tried: /usr/lib/php/20180731/mosquitto.so (libmosquitto.so.1: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/mosquitto.so.so (/usr/lib/php/20180731/mosquitto.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`
Le broker n'est pas sur la machine jeedom.

Une idée ?

**Comment by BadWolf42** [comment]
Bonjour Gis70,

Peux-tu nous donner plus d'information ?
Quel est ton setup : BoxJeedom, Pi, VM, OS, version du core etc ?
De quelle version de jMQTT as-tu upgradé vers la dernière beta ?
As-tu changé d'autres paramètres sur ton système depuis ?
Est-ce que mosquito était installé en local avant l'upgrade ?
As-tu complètement redémarré ton système depuis l'installation de la dernière beta ?

Es-tu à l'origine du [post suivant sur Community ](https://community.jeedom.com/t/unable-to-load-dynamic-library-mosquitto-so/63882)?

Merci,
Bad

**Comment by Gis70** [comment]
Bonjour,

Setup : VM Debian à jour.

J'ai dû upgrader de la beta d'une beta début juin vers la dernière.
Ce que j'ai fait en même temps c'est un apt update && upgrade pour être à jour.
Je n'ai jamais installé mosquitto en local.
Je n'ai pas redémarré depuis 140j.

Non ce n'est pas moi qui suis à l'origine de ce post, je vais tester la solution qui y est d'ailleurs.

**Comment by BadWolf42** [comment]
Un autre post Community du même genre est dispo [ici aussi](https://community.jeedom.com/t/probleme-mqtt-sur-php-7-3/30596/3).

@Domochip, c'est peut-être lié à ce commit https://github.com/Domochip/jMQTT/commit/04e29bc56e6dd1b6f9532484c5d4dc30c3cad1fe

**Comment by Gis70** [comment]
Merci, pour l'instant plus de message, ça à l'air de fonctionner.
