### ISSUE TITLE
single broker on jMQTT with 2 differents Jeedom causes instability

### ISSUE THREAD

**Issue by guldnerthomas** [BadWolf42/jMQTT#93]
Bonjour,

J'ai récemment migré d'un jeedom sur RPI3 vers un serveur Proxmox, j'ai installé mosquitto dans un container LXC. 
J'ai sauvegardé Jeedom sur mon RPI et restaurer cette sauvegarde sur ma VM sur Proxmox. J'ai voulu conservé mon RPI en tant qu'environnement de test, malheureusement je rencontre un conflit, le broker ne semble pas pouvoir être lancé sur mes 2 Jeedom simultanément. Lorsque le broker est lancé sur un Jeedom, l'autre broker se fait déconnecter et vice versa.
Le problème ne semble pas venir de Mosquitto car je n'ai pas de problème lorsque le broker jMQTT est connecté et que je suis également connecté avec MQTT Explorer.

![1](https://user-images.githubusercontent.com/64778687/128888255-3c6abae9-de07-4205-8ac5-3005c4ba0c5f.PNG)
![2](https://user-images.githubusercontent.com/64778687/128888284-47c8f02e-3e29-406a-ad7b-5bb2b1f8d99c.PNG)

Donc je me demande si cela résulte d'un bug lié a la réutilisation de ma sauvegarde et au fait que jMQTT requête de la même manière depuis les 2 Jeedom (avec un identifiant unique qui serait cloné "a cause" de la sauvegarde par exemple)

Les logs de debug indiquent ceci :
```
[2021-08-10 16:49:34][DEBUG] : broker msg: disconnected unexpectedly
[2021-08-10 16:49:34][WARNING] : exception thrown by MQTT client: The connection was lost.
[2021-08-10 16:49:34][INFO] : relance le démon dans 15s
```

Edit : en complément d'info je me rends compte que j'utilise toujours la version de jMQTT via les sources Github et non celle disponible sur le market. (peut etre que la sauvegarde/restauration d'un plugin provenant de github n'est pas gérée de la meme maniere qu'avec un plugin du market ?)

Edit 2 : Je crois avoir trouvé la réponse a mon probleme sur le github de l'ancien dev : https://github.com/domotruc/jMQTT/issues/109#issuecomment-814958049
J'utilise probablement le même clientID, si c'est le cas, comment puis je le changer afin de pouvoir utiliser 2 fois le plugin jMQTT dans des Jeedom différents ?

Merci d'avance

**Comment by BadWolf42** [comment]
Hello @guldnerthomas, 

En effet, il faut utiliser un ClientId différent par client MQTT sur un même Broker, donc par installation jMQTT.
Il peut être modifié dans la configuration du Broker, dans l'onglet Broker :
![image](https://user-images.githubusercontent.com/8396512/128894492-70bd4907-7c17-4a13-9442-044cd36d00c9.png)

Bonne soirée,
Bad

**Comment by guldnerthomas** [comment]
Merci pour l'information :)
